//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trascend.Bolet.AccesoDatos.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NHibernateConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NHibernateConfiguration() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trascend.Bolet.AccesoDatos.Recursos.NHibernateConfiguration", typeof(NHibernateConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOLET.
        /// </summary>
        public static string NHibernateClaveBD {
            get {
                return ResourceManager.GetString("NHibernateClaveBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NHibernate.Dialect.Oracle10gDialect.
        /// </summary>
        public static string NHibernateDialect {
            get {
                return ResourceManager.GetString("NHibernateDialect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NHibernate.Driver.OracleClientDriver.
        /// </summary>
        public static string NHibernateDriverClass {
            get {
                return ResourceManager.GetString("NHibernateDriverClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.1.164)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=PROD))).
        /// </summary>
        public static string NHibernateRutaBDDataSource {
            get {
                return ResourceManager.GetString("NHibernateRutaBDDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOLET.
        /// </summary>
        public static string NHibernateUsuarioBD {
            get {
                return ResourceManager.GetString("NHibernateUsuarioBD", resourceCulture);
            }
        }
    }
}
