'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Recursos
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Errores
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Diginsoft.Bolet.AccesoDatos.Errores", GetType(Errores).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocurrió un error consultando todos.
        '''</summary>
        Public Shared ReadOnly Property ExConsultarTodos() As String
            Get
                Return ResourceManager.GetString("ExConsultarTodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocurrió un error al consultar en base de datos los objetos filtrando por un objeto.
        '''</summary>
        Public Shared ReadOnly Property ExConsultarTodosObjetosPorObjeto() As String
            Get
                Return ResourceManager.GetString("ExConsultarTodosObjetosPorObjeto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocurrió un error al consultar en base de datos los roles filtrando por un rol.
        '''</summary>
        Public Shared ReadOnly Property ExConsultarTodosRolesPorRol() As String
            Get
                Return ResourceManager.GetString("ExConsultarTodosRolesPorRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocurrió un error al consultar en base de datos los usuarios filtrando por un usuario.
        '''</summary>
        Public Shared ReadOnly Property ExConsultarTodosUsuariosPorUsuario() As String
            Get
                Return ResourceManager.GetString("ExConsultarTodosUsuariosPorUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocurrió un error eliminando.
        '''</summary>
        Public Shared ReadOnly Property ExEliminando() As String
            Get
                Return ResourceManager.GetString("ExEliminando", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocurrió un error insertando o modificando datos.
        '''</summary>
        Public Shared ReadOnly Property ExInsertarOModificar() As String
            Get
                Return ResourceManager.GetString("ExInsertarOModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocurrió un error consultando por id.
        '''</summary>
        Public Shared ReadOnly Property ExObtenerPorId() As String
            Get
                Return ResourceManager.GetString("ExObtenerPorId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocurrió un error filtrando las Patentes.
        '''</summary>
        Public Shared ReadOnly Property ExPatentesFiltro() As String
            Get
                Return ResourceManager.GetString("ExPatentesFiltro", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
