//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trascend.Bolet.Cliente.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ids {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ids() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trascend.Bolet.Cliente.Recursos.Ids", typeof(Ids).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string Agente {
            get {
                return ResourceManager.GetString("Agente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string AgregarAgente {
            get {
                return ResourceManager.GetString("AgregarAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string AgregarAsociado {
            get {
                return ResourceManager.GetString("AgregarAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTBOLETIN.
        /// </summary>
        public static string AgregarBoletin {
            get {
                return ResourceManager.GetString("AgregarBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string AgregarCarta {
            get {
                return ResourceManager.GetString("AgregarCarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string AgregarEntradaAlterna {
            get {
                return ResourceManager.GetString("AgregarEntradaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_ESTADOS.
        /// </summary>
        public static string AgregarEstado {
            get {
                return ResourceManager.GetString("AgregarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TESTADOS.
        /// </summary>
        public static string AgregarEstatus {
            get {
                return ResourceManager.GetString("AgregarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string AgregarInfoAdicional {
            get {
                return ResourceManager.GetString("AgregarInfoAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string AgregarInfoBol {
            get {
                return ResourceManager.GetString("AgregarInfoBol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_INTERESADOS.
        /// </summary>
        public static string AgregarInteresado {
            get {
                return ResourceManager.GetString("AgregarInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTINT.
        /// </summary>
        public static string AgregarInternacional {
            get {
                return ResourceManager.GetString("AgregarInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_CONJUST.
        /// </summary>
        public static string AgregarJustificacion {
            get {
                return ResourceManager.GetString("AgregarJustificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_MARCAS.
        /// </summary>
        public static string AgregarMarca {
            get {
                return ResourceManager.GetString("AgregarMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTNAC.
        ///   Looks up a localized string similar to MYP_MACA_TER.
        /// </summary>
        public static string AgregarMarcaTercero {
            get {
                return ResourceManager.GetString("AgregarMarcaTercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYPTNAC.
        /// </summary>
        public static string AgregarNacional {
            get {
                return ResourceManager.GetString("AgregarNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTOBJ.
        /// </summary>
        public static string AgregarObjeto {
            get {
                return ResourceManager.GetString("AgregarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string AgregarOperacion {
            get {
                return ResourceManager.GetString("AgregarOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PAISES.
        /// </summary>
        public static string AgregarPais {
            get {
                return ResourceManager.GetString("AgregarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PODERES.
        /// </summary>
        public static string AgregarPoder {
            get {
                return ResourceManager.GetString("AgregarPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string AgregarRemitente {
            get {
                return ResourceManager.GetString("AgregarRemitente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_RESOLBOL.
        /// </summary>
        public static string AgregarResolucion {
            get {
                return ResourceManager.GetString("AgregarResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string AgregarResumen {
            get {
                return ResourceManager.GetString("AgregarResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGMROL.
        /// </summary>
        public static string AgregarRol {
            get {
                return ResourceManager.GetString("AgregarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TIPO_BASE.
        /// </summary>
        public static string AgregarTipoBase {
            get {
                return ResourceManager.GetString("AgregarTipoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TFECHAS.
        /// </summary>
        public static string AgregarTipoFecha {
            get {
                return ResourceManager.GetString("AgregarTipoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TINFOBOL.
        /// </summary>
        public static string AgregarTipoInfobol {
            get {
                return ResourceManager.GetString("AgregarTipoInfobol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTUSU.
        /// </summary>
        public static string AgregarUsuario {
            get {
                return ResourceManager.GetString("AgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAANEXO.
        /// </summary>
        public static string Anexo {
            get {
                return ResourceManager.GetString("Anexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string Asociado {
            get {
                return ResourceManager.GetString("Asociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTBOLETIN.
        /// </summary>
        public static string Boletin {
            get {
                return ResourceManager.GetString("Boletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_MARCAS_BSQ.
        /// </summary>
        public static string Busqueda {
            get {
                return ResourceManager.GetString("Busqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string Carta {
            get {
                return ResourceManager.GetString("Carta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COR_TENTRADA.
        /// </summary>
        public static string Categoria {
            get {
                return ResourceManager.GetString("Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMABAM.
        /// </summary>
        public static string ConsultarAbandonos {
            get {
                return ResourceManager.GetString("ConsultarAbandonos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarAgente {
            get {
                return ResourceManager.GetString("ConsultarAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarAgentes {
            get {
                return ResourceManager.GetString("ConsultarAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string ConsultarAsociado {
            get {
                return ResourceManager.GetString("ConsultarAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string ConsultarAsociados {
            get {
                return ResourceManager.GetString("ConsultarAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTBOLETIN.
        /// </summary>
        public static string ConsultarBoletin {
            get {
                return ResourceManager.GetString("ConsultarBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMPETM.
        /// </summary>
        public static string ConsultarCambioPeticionarios {
            get {
                return ResourceManager.GetString("ConsultarCambioPeticionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMDOMM.
        /// </summary>
        public static string ConsultarCambiosDeDomicilio {
            get {
                return ResourceManager.GetString("ConsultarCambiosDeDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_MNOMM.
        /// </summary>
        public static string ConsultarCambiosDeNombre {
            get {
                return ResourceManager.GetString("ConsultarCambiosDeNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarCarta {
            get {
                return ResourceManager.GetString("ConsultarCarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarCartas {
            get {
                return ResourceManager.GetString("ConsultarCartas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPCESM.
        /// </summary>
        public static string ConsultarCesiones {
            get {
                return ResourceManager.GetString("ConsultarCesiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_CONTACTOS.
        /// </summary>
        public static string ConsultarContacto {
            get {
                return ResourceManager.GetString("ConsultarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASO_TRANF.
        /// </summary>
        public static string ConsultarDatosTransferencia {
            get {
                return ResourceManager.GetString("ConsultarDatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarEntradaAlterna {
            get {
                return ResourceManager.GetString("ConsultarEntradaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarEntradaAlternas {
            get {
                return ResourceManager.GetString("ConsultarEntradaAlternas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_ESTADOS.
        /// </summary>
        public static string ConsultarEstado {
            get {
                return ResourceManager.GetString("ConsultarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TESTADOS.
        /// </summary>
        public static string ConsultarEstatus {
            get {
                return ResourceManager.GetString("ConsultarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TESTADOS.
        /// </summary>
        public static string ConsultarEstatuses {
            get {
                return ResourceManager.GetString("ConsultarEstatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMFUSM.
        /// </summary>
        public static string ConsultarFusiones {
            get {
                return ResourceManager.GetString("ConsultarFusiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarInfoAdicional {
            get {
                return ResourceManager.GetString("ConsultarInfoAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarInfoAdicionales {
            get {
                return ResourceManager.GetString("ConsultarInfoAdicionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarInfoBol {
            get {
                return ResourceManager.GetString("ConsultarInfoBol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarInfoBoles {
            get {
                return ResourceManager.GetString("ConsultarInfoBoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_INTERESADOS.
        /// </summary>
        public static string ConsultarInteresado {
            get {
                return ResourceManager.GetString("ConsultarInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTINT.
        /// </summary>
        public static string ConsultarInternacional {
            get {
                return ResourceManager.GetString("ConsultarInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTINT.
        /// </summary>
        public static string ConsultarInternacionales {
            get {
                return ResourceManager.GetString("ConsultarInternacionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASO_JUST.
        /// </summary>
        public static string ConsultarJustificaciones {
            get {
                return ResourceManager.GetString("ConsultarJustificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_MLICM.
        /// </summary>
        public static string ConsultarLicencia {
            get {
                return ResourceManager.GetString("ConsultarLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_MARCAS.
        /// </summary>
        public static string ConsultarMarca {
            get {
                return ResourceManager.GetString("ConsultarMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_MARCAS.
        /// </summary>
        public static string ConsultarMarcas {
            get {
                return ResourceManager.GetString("ConsultarMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTNAC.
        ///   Looks up a localized string similar to MYP_MARCA_TER.
        /// </summary>
        public static string ConsultarMarcasTercero {
            get {
                return ResourceManager.GetString("ConsultarMarcasTercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYP_MARCA_TER.
        /// </summary>
        public static string ConsultarMarcaTercero {
            get {
                return ResourceManager.GetString("ConsultarMarcaTercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYPTNAC.
        /// </summary>
        public static string ConsultarNacional {
            get {
                return ResourceManager.GetString("ConsultarNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTNAC.
        /// </summary>
        public static string ConsultarNacionales {
            get {
                return ResourceManager.GetString("ConsultarNacionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTOBJ.
        /// </summary>
        public static string ConsultarObjeto {
            get {
                return ResourceManager.GetString("ConsultarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTOBJ.
        /// </summary>
        public static string ConsultarObjetos {
            get {
                return ResourceManager.GetString("ConsultarObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarOperacion {
            get {
                return ResourceManager.GetString("ConsultarOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarOperaciones {
            get {
                return ResourceManager.GetString("ConsultarOperaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PAISES.
        /// </summary>
        public static string ConsultarPais {
            get {
                return ResourceManager.GetString("ConsultarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PAISES.
        /// </summary>
        public static string ConsultarPaises {
            get {
                return ResourceManager.GetString("ConsultarPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PODERES.
        /// </summary>
        public static string ConsultarPoder {
            get {
                return ResourceManager.GetString("ConsultarPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PODERES.
        /// </summary>
        public static string ConsultarPoderes {
            get {
                return ResourceManager.GetString("ConsultarPoderes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarRemitente {
            get {
                return ResourceManager.GetString("ConsultarRemitente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarRemitentes {
            get {
                return ResourceManager.GetString("ConsultarRemitentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_RENOVACIONES.
        /// </summary>
        public static string ConsultarRenovaciones {
            get {
                return ResourceManager.GetString("ConsultarRenovaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_RESOLBOL.
        /// </summary>
        public static string ConsultarResolucion {
            get {
                return ResourceManager.GetString("ConsultarResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_RESOLBOL.
        /// </summary>
        public static string ConsultarResoluciones {
            get {
                return ResourceManager.GetString("ConsultarResoluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarResuemenes {
            get {
                return ResourceManager.GetString("ConsultarResuemenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ConsultarResumen {
            get {
                return ResourceManager.GetString("ConsultarResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGMROL.
        /// </summary>
        public static string ConsultarRol {
            get {
                return ResourceManager.GetString("ConsultarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGMROL.
        /// </summary>
        public static string ConsultarRoles {
            get {
                return ResourceManager.GetString("ConsultarRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TIPO_BASE.
        /// </summary>
        public static string ConsultarTipoBase {
            get {
                return ResourceManager.GetString("ConsultarTipoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TFECHAS.
        /// </summary>
        public static string ConsultarTipoFecha {
            get {
                return ResourceManager.GetString("ConsultarTipoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TFECHAS.
        /// </summary>
        public static string ConsultarTipoFechas {
            get {
                return ResourceManager.GetString("ConsultarTipoFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TINFOBOL.
        /// </summary>
        public static string ConsultarTipoInfobol {
            get {
                return ResourceManager.GetString("ConsultarTipoInfobol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TINFOBOL.
        /// </summary>
        public static string ConsultarTipoInfoboles {
            get {
                return ResourceManager.GetString("ConsultarTipoInfoboles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TIPO_BASE.
        /// </summary>
        public static string ConsultarTiposBase {
            get {
                return ResourceManager.GetString("ConsultarTiposBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTUSU.
        /// </summary>
        public static string ConsultarUsuario {
            get {
                return ResourceManager.GetString("ConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTUSU.
        /// </summary>
        public static string ConsultarUsuarios {
            get {
                return ResourceManager.GetString("ConsultarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_CONTACTOS.
        /// </summary>
        public static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASO_TRANF.
        /// </summary>
        public static string DatosTransferencia {
            get {
                return ResourceManager.GetString("DatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string EliminarAsociado {
            get {
                return ResourceManager.GetString("EliminarAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTBOLETIN.
        /// </summary>
        public static string EliminarBoletin {
            get {
                return ResourceManager.GetString("EliminarBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string EliminarCarta {
            get {
                return ResourceManager.GetString("EliminarCarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASO_TRANF.
        /// </summary>
        public static string EliminarDatosTransferencia {
            get {
                return ResourceManager.GetString("EliminarDatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string EliminarEntradaAlterna {
            get {
                return ResourceManager.GetString("EliminarEntradaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_ESTADOS.
        /// </summary>
        public static string EliminarEstado {
            get {
                return ResourceManager.GetString("EliminarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TESTADOS.
        /// </summary>
        public static string EliminarEstatus {
            get {
                return ResourceManager.GetString("EliminarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TFECHAS.
        /// </summary>
        public static string EliminarFecha {
            get {
                return ResourceManager.GetString("EliminarFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string EliminarInfoAdicional {
            get {
                return ResourceManager.GetString("EliminarInfoAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string EliminarInfoBol {
            get {
                return ResourceManager.GetString("EliminarInfoBol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_INTERESADOS.
        /// </summary>
        public static string EliminarInteresado {
            get {
                return ResourceManager.GetString("EliminarInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTINT.
        /// </summary>
        public static string EliminarInternacional {
            get {
                return ResourceManager.GetString("EliminarInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTUSU.
        /// </summary>
        public static string EliminarMarca {
            get {
                return ResourceManager.GetString("EliminarMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTNAC.
        /// </summary>
        public static string EliminarNacional {
            get {
                return ResourceManager.GetString("EliminarNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTOBJ.
        /// </summary>
        public static string EliminarObjeto {
            get {
                return ResourceManager.GetString("EliminarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string EliminarOperacion {
            get {
                return ResourceManager.GetString("EliminarOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PAISES.
        /// </summary>
        public static string EliminarPais {
            get {
                return ResourceManager.GetString("EliminarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PODERES.
        /// </summary>
        public static string EliminarPoder {
            get {
                return ResourceManager.GetString("EliminarPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTBOLETIN.
        /// </summary>
        public static string EliminarRemitente {
            get {
                return ResourceManager.GetString("EliminarRemitente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_RESOLBOL.
        /// </summary>
        public static string EliminarResolucion {
            get {
                return ResourceManager.GetString("EliminarResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string EliminarResumen {
            get {
                return ResourceManager.GetString("EliminarResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGMROL.
        /// </summary>
        public static string EliminarRol {
            get {
                return ResourceManager.GetString("EliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TINFOBOL.
        /// </summary>
        public static string EliminarTipoInfobol {
            get {
                return ResourceManager.GetString("EliminarTipoInfobol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTUSU.
        /// </summary>
        public static string EliminarUsuario {
            get {
                return ResourceManager.GetString("EliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string EntradaAlterna {
            get {
                return ResourceManager.GetString("EntradaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_ESTADOS.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TESTADOS.
        /// </summary>
        public static string Estatus {
            get {
                return ResourceManager.GetString("Estatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMABAM.
        /// </summary>
        public static string GestionarAbandono {
            get {
                return ResourceManager.GetString("GestionarAbandono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMDOMM.
        /// </summary>
        public static string GestionarCambioDeDomicilio {
            get {
                return ResourceManager.GetString("GestionarCambioDeDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMNOMM.
        ///   Looks up a localized string similar to MYPMNOMM.
        /// </summary>
        public static string GestionarCambioDeNombre {
            get {
                return ResourceManager.GetString("GestionarCambioDeNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMPETM.
        /// </summary>
        public static string GestionarCambioPeticionario {
            get {
                return ResourceManager.GetString("GestionarCambioPeticionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMCESM.
        /// </summary>
        public static string GestionarCesion {
            get {
                return ResourceManager.GetString("GestionarCesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMFUSM.
        /// </summary>
        public static string GestionarFusion {
            get {
                return ResourceManager.GetString("GestionarFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMLICM.
        ///   Looks up a localized string similar to MYPMLICM.
        /// </summary>
        public static string GestionarLicencias {
            get {
                return ResourceManager.GetString("GestionarLicencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPMRENM.
        /// </summary>
        public static string GestionarRenovacion {
            get {
                return ResourceManager.GetString("GestionarRenovacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string InfoAdicional {
            get {
                return ResourceManager.GetString("InfoAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string InfoBol {
            get {
                return ResourceManager.GetString("InfoBol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_INTERESADOS.
        /// </summary>
        public static string Interesado {
            get {
                return ResourceManager.GetString("Interesado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTINAC.
        /// </summary>
        public static string Internacional {
            get {
                return ResourceManager.GetString("Internacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEG_AUDITORIAS.
        /// </summary>
        public static string ListaAuditorias {
            get {
                return ResourceManager.GetString("ListaAuditorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASO_TRANF.
        /// </summary>
        public static string ListaDatosTransferencia {
            get {
                return ResourceManager.GetString("ListaDatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LST_PODERES.
        /// </summary>
        public static string ListaPoderes {
            get {
                return ResourceManager.GetString("ListaPoderes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_MARCAS.
        /// </summary>
        public static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEDIO.
        /// </summary>
        public static string Medio {
            get {
                return ResourceManager.GetString("Medio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string ModificarAsociado {
            get {
                return ResourceManager.GetString("ModificarAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTBOLETIN.
        /// </summary>
        public static string ModificarBoletin {
            get {
                return ResourceManager.GetString("ModificarBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ModificarCarta {
            get {
                return ResourceManager.GetString("ModificarCarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASO_TRANF.
        /// </summary>
        public static string ModificarDatosTransferencia {
            get {
                return ResourceManager.GetString("ModificarDatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string ModificarEntradaAlterna {
            get {
                return ResourceManager.GetString("ModificarEntradaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_ESTADOS.
        /// </summary>
        public static string ModificarEstado {
            get {
                return ResourceManager.GetString("ModificarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TESTADOS.
        /// </summary>
        public static string ModificarEstatus {
            get {
                return ResourceManager.GetString("ModificarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TFECHAS.
        /// </summary>
        public static string ModificarFecha {
            get {
                return ResourceManager.GetString("ModificarFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string ModificarInfoAdicional {
            get {
                return ResourceManager.GetString("ModificarInfoAdicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASOCIADOS.
        /// </summary>
        public static string ModificarInfoBol {
            get {
                return ResourceManager.GetString("ModificarInfoBol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_INTERESADOS.
        /// </summary>
        public static string ModificarInteresado {
            get {
                return ResourceManager.GetString("ModificarInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTINT.
        /// </summary>
        public static string ModificarInternacional {
            get {
                return ResourceManager.GetString("ModificarInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_MARCAS.
        /// </summary>
        public static string ModificarMarca {
            get {
                return ResourceManager.GetString("ModificarMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTNAC.
        /// </summary>
        public static string ModificarNacional {
            get {
                return ResourceManager.GetString("ModificarNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTOBJ.
        /// </summary>
        public static string ModificarObjeto {
            get {
                return ResourceManager.GetString("ModificarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FAC_ASO_TRANF.
        /// </summary>
        public static string ModificarOperacion {
            get {
                return ResourceManager.GetString("ModificarOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PAISES.
        /// </summary>
        public static string ModificarPais {
            get {
                return ResourceManager.GetString("ModificarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PODERES.
        /// </summary>
        public static string ModificarPoder {
            get {
                return ResourceManager.GetString("ModificarPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_RESOLBOL.
        /// </summary>
        public static string ModificarResolucion {
            get {
                return ResourceManager.GetString("ModificarResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGMROL.
        /// </summary>
        public static string ModificarRol {
            get {
                return ResourceManager.GetString("ModificarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TINFOBOL.
        /// </summary>
        public static string ModificarTipoInfobol {
            get {
                return ResourceManager.GetString("ModificarTipoInfobol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTUSU.
        /// </summary>
        public static string ModificarUsuario {
            get {
                return ResourceManager.GetString("ModificarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTNAC.
        /// </summary>
        public static string Nacional {
            get {
                return ResourceManager.GetString("Nacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTOBJ.
        /// </summary>
        public static string Objeto {
            get {
                return ResourceManager.GetString("Objeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYPTAGENTE.
        /// </summary>
        public static string Operacion {
            get {
                return ResourceManager.GetString("Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PAISES.
        /// </summary>
        public static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_PODERES.
        /// </summary>
        public static string Poder {
            get {
                return ResourceManager.GetString("Poder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COR_REMI.
        /// </summary>
        public static string Remitente {
            get {
                return ResourceManager.GetString("Remitente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_RESOLBOL.
        /// </summary>
        public static string Resolucion {
            get {
                return ResourceManager.GetString("Resolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COR_RESUMEN.
        /// </summary>
        public static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGMROL.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TFECHAS.
        /// </summary>
        public static string TipoFecha {
            get {
                return ResourceManager.GetString("TipoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MYP_TINFOBOL.
        /// </summary>
        public static string TipoInfobol {
            get {
                return ResourceManager.GetString("TipoInfobol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COR_TRANSFE.
        /// </summary>
        public static string TransferenciaPlantilla {
            get {
                return ResourceManager.GetString("TransferenciaPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEGTUSU.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
