//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trascend.Bolet.Cliente.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensajesConElUsuario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesConElUsuario() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trascend.Bolet.Cliente.Recursos.MensajesConElUsuario", typeof(MensajesConElUsuario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandono eliminado con éxito.
        /// </summary>
        internal static string AbandonoEliminado {
            get {
                return ResourceManager.GetString("AbandonoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandono insertado con éxito.
        /// </summary>
        internal static string AbandonoInsertado {
            get {
                return ResourceManager.GetString("AbandonoInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente eliminado con éxito.
        /// </summary>
        internal static string AgenteEliminado {
            get {
                return ResourceManager.GetString("AgenteEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente insertado con éxito.
        /// </summary>
        internal static string AgenteInsertado {
            get {
                return ResourceManager.GetString("AgenteInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agente modificado con éxito.
        /// </summary>
        internal static string AgenteModificado {
            get {
                return ResourceManager.GetString("AgenteModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el Agente {0} no aparece en el Poder de alguna de las Marcas seleccionadas.
        /// </summary>
        internal static string AlertaAgenteNoApareceEnPoderDeMarca {
            get {
                return ResourceManager.GetString("AlertaAgenteNoApareceEnPoderDeMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el Agente {0} no aparece en el Poder de alguna de los Patentes seleccionados.
        /// </summary>
        internal static string AlertaAgenteNoApareceEnPoderDePatente {
            get {
                return ResourceManager.GetString("AlertaAgenteNoApareceEnPoderDePatente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el Agente {0} no posee Poderes relacionados con alguna de los Interesados seleccionadas.
        /// </summary>
        internal static string AlertaAgenteNoPoseePoderConInteresado {
            get {
                return ResourceManager.GetString("AlertaAgenteNoPoseePoderConInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el Escrito debe tener un agente seleccionado.
        /// </summary>
        internal static string AlertaEscritoSinAgente {
            get {
                return ResourceManager.GetString("AlertaEscritoSinAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el Escrito debe tener al menos un Boletín.
        /// </summary>
        internal static string AlertaEscritoSinBoletin {
            get {
                return ResourceManager.GetString("AlertaEscritoSinBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disuclpe El Escrito No Tiene Ninguna Busqueda Seleccionada.
        /// </summary>
        internal static string AlertaEscritoSinBusqueda {
            get {
                return ResourceManager.GetString("AlertaEscritoSinBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe El Escrito No Tiene Calificativo De Nombre De marca.
        /// </summary>
        internal static string AlertaEscritoSinCalificativoDeMarca {
            get {
                return ResourceManager.GetString("AlertaEscritoSinCalificativoDeMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el escrito no tiene Corrección.
        /// </summary>
        internal static string AlertaEscritoSinCorreccion {
            get {
                return ResourceManager.GetString("AlertaEscritoSinCorreccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el escrito no posee Error definido.
        /// </summary>
        internal static string AlertaEscritoSinError {
            get {
                return ResourceManager.GetString("AlertaEscritoSinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe El Escrito no Tiene Fecha De Presentacion.
        /// </summary>
        internal static string AlertaEscritoSinFecha {
            get {
                return ResourceManager.GetString("AlertaEscritoSinFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el Escrito debe tener al menos un Interesado.
        /// </summary>
        internal static string AlertaEscritoSinInteresados {
            get {
                return ResourceManager.GetString("AlertaEscritoSinInteresados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el Escrito debe tener al menos una marca.
        /// </summary>
        internal static string AlertaEscritoSinMarcas {
            get {
                return ResourceManager.GetString("AlertaEscritoSinMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el escrito no posee Numeral definido.
        /// </summary>
        internal static string AlertaEscritoSinNumeral {
            get {
                return ResourceManager.GetString("AlertaEscritoSinNumeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el Escrito debe tener al menos una Resolución.
        /// </summary>
        internal static string AlertaEscritoSinPatentes {
            get {
                return ResourceManager.GetString("AlertaEscritoSinPatentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el Escrito debe tener al menos una Resolución.
        /// </summary>
        internal static string AlertaEscritoSinResolucion {
            get {
                return ResourceManager.GetString("AlertaEscritoSinResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el escrito no tiene tipo de corrección voluntaria.
        /// </summary>
        internal static string AlertaEscritoSinTipoCorreccionVoluntaria {
            get {
                return ResourceManager.GetString("AlertaEscritoSinTipoCorreccionVoluntaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Marca a tercero Requiere un Asociado.
        /// </summary>
        internal static string AlertaMarcaTerceroSinAsociado {
            get {
                return ResourceManager.GetString("AlertaMarcaTerceroSinAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Marca a tercero Requiere un Interesado.
        /// </summary>
        internal static string AlertaMarcaTerceroSinInteresado {
            get {
                return ResourceManager.GetString("AlertaMarcaTerceroSinInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Marca a tercero Debe Tener un Nombre Asignado.
        /// </summary>
        internal static string AlertaMarcaTerceroSinNombre {
            get {
                return ResourceManager.GetString("AlertaMarcaTerceroSinNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Marca a tercero Requiere una Situacion.
        /// </summary>
        internal static string AlertaMarcaTerceroSinSituacion {
            get {
                return ResourceManager.GetString("AlertaMarcaTerceroSinSituacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anexo insertado con éxito.
        /// </summary>
        internal static string AnexoInsertado {
            get {
                return ResourceManager.GetString("AnexoInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anexo Modificado con éxito.
        /// </summary>
        internal static string AnexoModificado {
            get {
                return ResourceManager.GetString("AnexoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anualidad Eliminada Con Exito.
        /// </summary>
        internal static string AnualidadEliminada {
            get {
                return ResourceManager.GetString("AnualidadEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anualdiad Insertada Con Exito.
        /// </summary>
        internal static string AnualidadInsertada {
            get {
                return ResourceManager.GetString("AnualidadInsertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anualidad Modificada Con Exito.
        /// </summary>
        internal static string AnualidadModificada {
            get {
                return ResourceManager.GetString("AnualidadModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociado eliminado con éxito.
        /// </summary>
        internal static string AsociadoEliminado {
            get {
                return ResourceManager.GetString("AsociadoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociado insertado con éxito.
        /// </summary>
        internal static string AsociadoInsertado {
            get {
                return ResourceManager.GetString("AsociadoInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asociado modificado con éxito.
        /// </summary>
        internal static string AsociadoModificado {
            get {
                return ResourceManager.GetString("AsociadoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boletín eliminado con éxito.
        /// </summary>
        internal static string BoletinEliminado {
            get {
                return ResourceManager.GetString("BoletinEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boletín insertado con éxito.
        /// </summary>
        internal static string BoletinInsertado {
            get {
                return ResourceManager.GetString("BoletinInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boletín modificado con éxito.
        /// </summary>
        internal static string BoletinModificado {
            get {
                return ResourceManager.GetString("BoletinModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de domicilio eliminado con éxito.
        /// </summary>
        internal static string CambioDeDomicilioEliminado {
            get {
                return ResourceManager.GetString("CambioDeDomicilioEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de domicilio insertado con éxito.
        /// </summary>
        internal static string CambioDeDomicilioInsertado {
            get {
                return ResourceManager.GetString("CambioDeDomicilioInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de domicilio modificado con éxito.
        /// </summary>
        internal static string CambioDeDomicilioModificado {
            get {
                return ResourceManager.GetString("CambioDeDomicilioModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de nombre eliminado con éxito.
        /// </summary>
        internal static string CambioDeNombreEliminado {
            get {
                return ResourceManager.GetString("CambioDeNombreEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de nombre insertado con éxito.
        /// </summary>
        internal static string CambioDeNombreInsertado {
            get {
                return ResourceManager.GetString("CambioDeNombreInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de nombre modificado con éxito.
        /// </summary>
        internal static string CambioDeNombreModificado {
            get {
                return ResourceManager.GetString("CambioDeNombreModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio peticionario eliminado con éxito.
        /// </summary>
        internal static string CambioPeticionarioEliminado {
            get {
                return ResourceManager.GetString("CambioPeticionarioEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de peticionario insertado con éxito.
        /// </summary>
        internal static string CambioPeticionarioInsertado {
            get {
                return ResourceManager.GetString("CambioPeticionarioInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de peticionario modificado con éxito.
        /// </summary>
        internal static string CambioPeticionarioModificado {
            get {
                return ResourceManager.GetString("CambioPeticionarioModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carta insertada con éxito.
        /// </summary>
        internal static string CartaInsertada {
            get {
                return ResourceManager.GetString("CartaInsertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carta modificada con éxito.
        /// </summary>
        internal static string CartaModificada {
            get {
                return ResourceManager.GetString("CartaModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría eliminada con éxito.
        /// </summary>
        internal static string CategoriaEliminado {
            get {
                return ResourceManager.GetString("CategoriaEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría agregada con éxito.
        /// </summary>
        internal static string CategoriaInsertado {
            get {
                return ResourceManager.GetString("CategoriaInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría modificada con éxito.
        /// </summary>
        internal static string CategoriaModificado {
            get {
                return ResourceManager.GetString("CategoriaModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cesión eliminada con éxito.
        /// </summary>
        internal static string CesionEliminada {
            get {
                return ResourceManager.GetString("CesionEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cesión insertada con éxito.
        /// </summary>
        internal static string CesionInsertada {
            get {
                return ResourceManager.GetString("CesionInsertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cesión modificada con éxito.
        /// </summary>
        internal static string CesionModificada {
            get {
                return ResourceManager.GetString("CesionModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea duplicar la Marca?.
        /// </summary>
        internal static string ConfirmacionDuplicarMarca {
            get {
                return ResourceManager.GetString("ConfirmacionDuplicarMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea duplicar la Marca Tercera?.
        /// </summary>
        internal static string ConfirmacionDuplicarMarcaTercero {
            get {
                return ResourceManager.GetString("ConfirmacionDuplicarMarcaTercero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el abandono?.
        /// </summary>
        internal static string ConfirmacionEliminarAbandono {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarAbandono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el agente?.
        /// </summary>
        internal static string ConfirmacionEliminarAgente {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el Anexo?.
        /// </summary>
        internal static string ConfirmacionEliminarAnexo {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el Asociado?.
        /// </summary>
        internal static string ConfirmacionEliminarAsociado {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el boletin?.
        /// </summary>
        internal static string ConfirmacionEliminarBoletin {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la Búsqueda?.
        /// </summary>
        internal static string ConfirmacionEliminarBusqueda {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el cambio de domicilio?.
        /// </summary>
        internal static string ConfirmacionEliminarCambioDeDomicilio {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarCambioDeDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el cambio nombre?.
        /// </summary>
        internal static string ConfirmacionEliminarCambioDeNombre {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarCambioDeNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el cambio peticionario?.
        /// </summary>
        internal static string ConfirmacionEliminarCambioPeticionario {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarCambioPeticionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la categoría?.
        /// </summary>
        internal static string ConfirmacionEliminarCategoria {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la cesión?.
        /// </summary>
        internal static string ConfirmacionEliminarCesion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarCesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que dese eliminar el contacto?.
        /// </summary>
        internal static string ConfirmacionEliminarContacto {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar los datos de la transferencia?.
        /// </summary>
        internal static string ConfirmacionEliminarDatosTransferencia {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarDatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la entrada alterna?.
        /// </summary>
        internal static string ConfirmacionEliminarEntradaAlterna {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarEntradaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el estado?.
        /// </summary>
        internal static string ConfirmacionEliminarEstado {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el estatus?.
        /// </summary>
        internal static string ConfirmacionEliminarEstatus {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la fusión?.
        /// </summary>
        internal static string ConfirmacionEliminarFusion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la info Bol?.
        /// </summary>
        internal static string ConfirmacionEliminarInfoBol {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarInfoBol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el interesado?.
        /// </summary>
        internal static string ConfirmacionEliminarInteresado {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la clase internacional?.
        /// </summary>
        internal static string ConfirmacionEliminarInternacional {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar el inventor?.
        /// </summary>
        internal static string ConfirmacionEliminarInventor {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarInventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la justificacion?.
        /// </summary>
        internal static string ConfirmacionEliminarJustificacion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarJustificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la licencia?.
        /// </summary>
        internal static string ConfirmacionEliminarLicencia {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el Medio?.
        /// </summary>
        internal static string ConfirmacionEliminarMedio {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la clase nacional?.
        /// </summary>
        internal static string ConfirmacionEliminarNacional {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el objeto?.
        /// </summary>
        internal static string ConfirmacionEliminarObjeto {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la operacion?.
        /// </summary>
        internal static string ConfirmacionEliminarOperacion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el país?.
        /// </summary>
        internal static string ConfirmacionEliminarPais {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el poder?.
        /// </summary>
        internal static string ConfirmacionEliminarPoder {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el remitente?.
        /// </summary>
        internal static string ConfirmacionEliminarRemitente {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarRemitente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar esta Renovacion?.
        /// </summary>
        internal static string ConfirmacionEliminarRenovacion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarRenovacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar la resolución?.
        /// </summary>
        internal static string ConfirmacionEliminarResolucion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que dese eliminar el Resumen?.
        /// </summary>
        internal static string ConfirmacionEliminarResumen {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el rol?.
        /// </summary>
        internal static string ConfirmacionEliminarRol {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea elimar este Tipo de Base?.
        /// </summary>
        internal static string ConfirmacionEliminarTipoBase {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarTipoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el tipo de Fecha?.
        /// </summary>
        internal static string ConfirmacionEliminarTipoFecha {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarTipoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el tipo de infobol?.
        /// </summary>
        internal static string ConfirmacionEliminarTipoInfobol {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarTipoInfobol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea eliminar el usuario?.
        /// </summary>
        internal static string ConfirmacionEliminarUsuario {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea genera el escrito para las {0} marcas?.
        /// </summary>
        internal static string ConfirmacionGenerarEscrito {
            get {
                return ResourceManager.GetString("ConfirmacionGenerarEscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea genera el escrito para las {0} interesado(s)?.
        /// </summary>
        internal static string ConfirmacionGenerarEscritoInteresado {
            get {
                return ResourceManager.GetString("ConfirmacionGenerarEscritoInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea genera el escrito para las {0} patentes?.
        /// </summary>
        internal static string ConfirmacionGenerarEscritoPatente {
            get {
                return ResourceManager.GetString("ConfirmacionGenerarEscritoPatente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que desea salir del Sistema?.
        /// </summary>
        internal static string ConfirmacionSalirDelSistema {
            get {
                return ResourceManager.GetString("ConfirmacionSalirDelSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esto modificará el Distingue. ¿Seguro que desea tomar clase internacional?.
        /// </summary>
        internal static string ConfirmacionTomarClaseInternacional {
            get {
                return ResourceManager.GetString("ConfirmacionTomarClaseInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plantillas transferidas con éxito.
        /// </summary>
        internal static string ConfirmacionTransferenciaPlantilla {
            get {
                return ResourceManager.GetString("ConfirmacionTransferenciaPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto insertado con éxito.
        /// </summary>
        internal static string ContactoInsertado {
            get {
                return ResourceManager.GetString("ContactoInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto modificado con éxito.
        /// </summary>
        internal static string ContactoModificado {
            get {
                return ResourceManager.GetString("ContactoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada alterna eliminado con éxito.
        /// </summary>
        internal static string EntradaAlternaEliminado {
            get {
                return ResourceManager.GetString("EntradaAlternaEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada alterna insertado con éxito.
        /// </summary>
        internal static string EntradaAlternaInsertado {
            get {
                return ResourceManager.GetString("EntradaAlternaInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrada alterna modificado con éxito.
        /// </summary>
        internal static string EntradaAlternaModificado {
            get {
                return ResourceManager.GetString("EntradaAlternaModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apoderado no posee poderes asociados con el {0}.
        /// </summary>
        internal static string ErrorAgenteNoPoseePoderConInteresado {
            get {
                return ResourceManager.GetString("ErrorAgenteNoPoseePoderConInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El agente que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorAgenteRepetido {
            get {
                return ResourceManager.GetString("ErrorAgenteRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe, ha ocurrido un error al generar el traspaso.
        /// </summary>
        internal static string ErrorAlGenerarTraspaso {
            get {
                return ResourceManager.GetString("ErrorAlGenerarTraspaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el archivo de la memoria no fue encontrado.
        /// </summary>
        internal static string ErrorArchivoMemoriaNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorArchivoMemoriaNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo del asociado no encontrado..
        /// </summary>
        internal static string ErrorAsociadoNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorAsociadoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El boletin que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorBoletinRepetido {
            get {
                return ResourceManager.GetString("ErrorBoletinRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La carta que introdujo no esta en el sistema..
        /// </summary>
        internal static string ErrorCartaNoEncontrada {
            get {
                return ResourceManager.GetString("ErrorCartaNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe la Carta de Código: {0} ya existe.
        /// </summary>
        internal static string ErrorCartaRepetida {
            get {
                return ResourceManager.GetString("ErrorCartaRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe el certificado no fue encontrado.
        /// </summary>
        internal static string ErrorCertificadoNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorCertificadoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido establecer conexión con el servidor.
        /// </summary>
        internal static string ErrorConexionServidor {
            get {
                return ResourceManager.GetString("ErrorConexionServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error consultando la patente. No existe el Asociado con código:.
        /// </summary>
        internal static string ErrorConsultandoAsociado {
            get {
                return ResourceManager.GetString("ErrorConsultandoAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error consultando la patente. No existe el Interesado con código:.
        /// </summary>
        internal static string ErrorConsultandoInteresado {
            get {
                return ResourceManager.GetString("ErrorConsultandoInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La correspondencia que introdujo no esta en el sistema..
        /// </summary>
        internal static string ErrorCorrespondenciaNoEncontrada {
            get {
                return ResourceManager.GetString("ErrorCorrespondenciaNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entrada alterna que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorEntradaAlternaRepetido {
            get {
                return ResourceManager.GetString("ErrorEntradaAlternaRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El estado que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorEstadoRepetido {
            get {
                return ResourceManager.GetString("ErrorEstadoRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El estatus que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorEstatusRepetido {
            get {
                return ResourceManager.GetString("ErrorEstatusRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe debe llenar al menos 1 filtro para la consulta.
        /// </summary>
        internal static string ErrorFiltroIncompleto {
            get {
                return ResourceManager.GetString("ErrorFiltroIncompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error generando el archivo {0}.
        /// </summary>
        internal static string ErrorGenerandoInformacionRecordatorio {
            get {
                return ResourceManager.GetString("ErrorGenerandoInformacionRecordatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error inesperado.
        /// </summary>
        internal static string ErrorInesperado {
            get {
                return ResourceManager.GetString("ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El {0} no posee poderes asociados con el apoderado.
        /// </summary>
        internal static string ErrorInteresadoNoPoseePoderConAgente {
            get {
                return ResourceManager.GetString("ErrorInteresadoNoPoseePoderConAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clase internacional que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorInternacionalRepetido {
            get {
                return ResourceManager.GetString("ErrorInternacionalRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe, el Id de la Memoria está repetido.
        /// </summary>
        internal static string ErrorMemoriaRepetida {
            get {
                return ResourceManager.GetString("ErrorMemoriaRepetida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La clase nacial que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorNacionalRepetido {
            get {
                return ResourceManager.GetString("ErrorNacionalRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El objeto que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorObjetoRepetido {
            get {
                return ResourceManager.GetString("ErrorObjetoRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La pais que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorPaisRepetido {
            get {
                return ResourceManager.GetString("ErrorPaisRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo del poder no encontrado..
        /// </summary>
        internal static string ErrorPoderNoEncontrado {
            get {
                return ResourceManager.GetString("ErrorPoderNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El remitente que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorRemitenteRepetido {
            get {
                return ResourceManager.GetString("ErrorRemitenteRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error con los objetos del servidor.
        /// </summary>
        internal static string ErrorRemoting {
            get {
                return ResourceManager.GetString("ErrorRemoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La resolucion que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorResolucionRepetido {
            get {
                return ResourceManager.GetString("ErrorResolucionRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Resumen que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorResumenRepetido {
            get {
                return ResourceManager.GetString("ErrorResumenRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorRolRepetido {
            get {
                return ResourceManager.GetString("ErrorRolRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Tipo de Base a insertar ya existe.
        /// </summary>
        internal static string ErrorTipoBaseRepetido {
            get {
                return ResourceManager.GetString("ErrorTipoBaseRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de fecha que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorTipoFechaRepetido {
            get {
                return ResourceManager.GetString("ErrorTipoFechaRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de infobol que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorTipoInfoBolRepetido {
            get {
                return ResourceManager.GetString("ErrorTipoInfoBolRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al transferir las plantillas.
        /// </summary>
        internal static string ErrorTransferenciaPlantilla {
            get {
                return ResourceManager.GetString("ErrorTransferenciaPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario que intenta introducir ya existe.
        /// </summary>
        internal static string ErrorUsuarioRepetido {
            get {
                return ResourceManager.GetString("ErrorUsuarioRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado eliminado con éxito.
        /// </summary>
        internal static string EstadoEliminado {
            get {
                return ResourceManager.GetString("EstadoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado insertado con éxito.
        /// </summary>
        internal static string EstadoInsertado {
            get {
                return ResourceManager.GetString("EstadoInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Marca eliminado con éxito.
        /// </summary>
        internal static string EstadoMarcaEliminado {
            get {
                return ResourceManager.GetString("EstadoMarcaEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Marca insertado con éxito.
        /// </summary>
        internal static string EstadoMarcaInsertado {
            get {
                return ResourceManager.GetString("EstadoMarcaInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Marca Modificado con éxito.
        /// </summary>
        internal static string EstadoMarcaModificado {
            get {
                return ResourceManager.GetString("EstadoMarcaModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado modificado con éxito.
        /// </summary>
        internal static string EstadoModificado {
            get {
                return ResourceManager.GetString("EstadoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus eliminado con éxito.
        /// </summary>
        internal static string EstatusEliminado {
            get {
                return ResourceManager.GetString("EstatusEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus insertado con éxito.
        /// </summary>
        internal static string EstatusInsertado {
            get {
                return ResourceManager.GetString("EstatusInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estatus modificado con éxito.
        /// </summary>
        internal static string EstatusModificado {
            get {
                return ResourceManager.GetString("EstatusModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe ha ocurrido un error con la comunicación entre el sistema y los paquetes de base de datos.
        /// </summary>
        internal static string ExcepcionPaquetes {
            get {
                return ResourceManager.GetString("ExcepcionPaquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo {0} se ha generado con éxito.
        /// </summary>
        internal static string ExitoGenerandoInformacionRecordatorio {
            get {
                return ResourceManager.GetString("ExitoGenerandoInformacionRecordatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fusión eliminada con éxito.
        /// </summary>
        internal static string FusionEliminada {
            get {
                return ResourceManager.GetString("FusionEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fusión insertada con éxito.
        /// </summary>
        internal static string FusionInsertada {
            get {
                return ResourceManager.GetString("FusionInsertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fusión modificada con éxito.
        /// </summary>
        internal static string FusionModificada {
            get {
                return ResourceManager.GetString("FusionModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o clave incorrectos.
        /// </summary>
        internal static string IdOClaveIncorrectos {
            get {
                return ResourceManager.GetString("IdOClaveIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar tanto el usuario como la contraseña.
        /// </summary>
        internal static string IdOClaveObligatorio {
            get {
                return ResourceManager.GetString("IdOClaveObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interesado eliminado con éxito.
        /// </summary>
        internal static string InteresadoEliminado {
            get {
                return ResourceManager.GetString("InteresadoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interesado insertado con éxito.
        /// </summary>
        internal static string InteresadoInsertado {
            get {
                return ResourceManager.GetString("InteresadoInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interesado modificado con éxito.
        /// </summary>
        internal static string InteresadoModificado {
            get {
                return ResourceManager.GetString("InteresadoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase internacional eliminado con éxito.
        /// </summary>
        internal static string InternacionalEliminado {
            get {
                return ResourceManager.GetString("InternacionalEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase internacional insertado con éxito.
        /// </summary>
        internal static string InternacionalInsertado {
            get {
                return ResourceManager.GetString("InternacionalInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase internacional modificado con éxito.
        /// </summary>
        internal static string InternacionalModificado {
            get {
                return ResourceManager.GetString("InternacionalModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justificación modificada con éxito.
        /// </summary>
        internal static string JustificacionModificado {
            get {
                return ResourceManager.GetString("JustificacionModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia eliminada con éxito.
        /// </summary>
        internal static string LicenciaEliminada {
            get {
                return ResourceManager.GetString("LicenciaEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia insertada con éxito.
        /// </summary>
        internal static string LicenciaInsertada {
            get {
                return ResourceManager.GetString("LicenciaInsertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia modificada con éxito.
        /// </summary>
        internal static string LicenciaModificada {
            get {
                return ResourceManager.GetString("LicenciaModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca insertada con éxito.
        /// </summary>
        internal static string MarcaInsertada {
            get {
                return ResourceManager.GetString("MarcaInsertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca modificada con éxito.
        /// </summary>
        internal static string MarcaModificada {
            get {
                return ResourceManager.GetString("MarcaModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La marca no tiene clase ¿Desea imprimir de todas maneras?.
        /// </summary>
        internal static string MarcaSinClase {
            get {
                return ResourceManager.GetString("MarcaSinClase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo descripción del signo está vacío ¿Desea imprimir de todas maneras?.
        /// </summary>
        internal static string MarcaSinDescripcionDelSigno {
            get {
                return ResourceManager.GetString("MarcaSinDescripcionDelSigno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La marca no tiene distingue ¿Desea imprimir de todas maneras?.
        /// </summary>
        internal static string MarcaSinDistingue {
            get {
                return ResourceManager.GetString("MarcaSinDistingue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La marca no tiene número de poder ¿Desea imprimir de todas maneras?.
        /// </summary>
        internal static string MarcaSinNumeroDePoder {
            get {
                return ResourceManager.GetString("MarcaSinNumeroDePoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca Tercero Eliminado con éxito.
        /// </summary>
        internal static string MarcaTerceroEliminado {
            get {
                return ResourceManager.GetString("MarcaTerceroEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MarcaTercero insertada con éxito.
        /// </summary>
        internal static string MarcaTerceroInsertada {
            get {
                return ResourceManager.GetString("MarcaTerceroInsertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca Tercero modificado con éxito.
        /// </summary>
        internal static string MarcaTerceroModificado {
            get {
                return ResourceManager.GetString("MarcaTerceroModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medio insertado con éxito.
        /// </summary>
        internal static string MedioInsertado {
            get {
                return ResourceManager.GetString("MedioInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medio modificado con éxito.
        /// </summary>
        internal static string MedioModificado {
            get {
                return ResourceManager.GetString("MedioModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Memoria eliminada con éxito.
        /// </summary>
        internal static string MemoriaEliminado {
            get {
                return ResourceManager.GetString("MemoriaEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Memoria insertada con éxito.
        /// </summary>
        internal static string MemoriaInsertado {
            get {
                return ResourceManager.GetString("MemoriaInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Memoria modificada con éxito.
        /// </summary>
        internal static string MemoriaModificado {
            get {
                return ResourceManager.GetString("MemoriaModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase nacional eliminado con éxito.
        /// </summary>
        internal static string NacionalEliminado {
            get {
                return ResourceManager.GetString("NacionalEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase nacional insertado con éxito.
        /// </summary>
        internal static string NacionalInsertado {
            get {
                return ResourceManager.GetString("NacionalInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase nacional modificado con éxito.
        /// </summary>
        internal static string NacionalModificado {
            get {
                return ResourceManager.GetString("NacionalModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe, no hay resultados para la búsqueda.
        /// </summary>
        internal static string NoHayResultados {
            get {
                return ResourceManager.GetString("NoHayResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto eliminado con éxito.
        /// </summary>
        internal static string ObjetoEliminado {
            get {
                return ResourceManager.GetString("ObjetoEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto insertado con éxito.
        /// </summary>
        internal static string ObjetoInsertado {
            get {
                return ResourceManager.GetString("ObjetoInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto modificado con éxito.
        /// </summary>
        internal static string ObjetoModificado {
            get {
                return ResourceManager.GetString("ObjetoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion eliminada con éxito.
        /// </summary>
        internal static string OperacionEliminado {
            get {
                return ResourceManager.GetString("OperacionEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion insertada con éxito.
        /// </summary>
        internal static string OperacionInsertado {
            get {
                return ResourceManager.GetString("OperacionInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion modificada con éxito.
        /// </summary>
        internal static string OperacionModificado {
            get {
                return ResourceManager.GetString("OperacionModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País eliminado con éxito.
        /// </summary>
        internal static string PaisEliminado {
            get {
                return ResourceManager.GetString("PaisEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País insertado con éxito.
        /// </summary>
        internal static string PaisInsertado {
            get {
                return ResourceManager.GetString("PaisInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País modificado con éxito.
        /// </summary>
        internal static string PaisModificado {
            get {
                return ResourceManager.GetString("PaisModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente modificada con éxito.
        /// </summary>
        internal static string PatenteModificada {
            get {
                return ResourceManager.GetString("PatenteModificada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poder eliminado con éxito.
        /// </summary>
        internal static string PoderEliminado {
            get {
                return ResourceManager.GetString("PoderEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poder insertado con éxito.
        /// </summary>
        internal static string PoderInsertado {
            get {
                return ResourceManager.GetString("PoderInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poder modificado con éxito.
        /// </summary>
        internal static string PoderModificado {
            get {
                return ResourceManager.GetString("PoderModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remitente eliminado con éxito.
        /// </summary>
        internal static string RemitenteEliminado {
            get {
                return ResourceManager.GetString("RemitenteEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remitente insertado con éxito.
        /// </summary>
        internal static string RemitenteInsertado {
            get {
                return ResourceManager.GetString("RemitenteInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remitente modificado con éxito.
        /// </summary>
        internal static string RemitenteModificado {
            get {
                return ResourceManager.GetString("RemitenteModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renovación eliminada con éxito.
        /// </summary>
        internal static string RenovacionEliminada {
            get {
                return ResourceManager.GetString("RenovacionEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renovación insertada con éxito.
        /// </summary>
        internal static string RenovacionInsertada {
            get {
                return ResourceManager.GetString("RenovacionInsertada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolución eliminada con éxito.
        /// </summary>
        internal static string ResolucionEliminado {
            get {
                return ResourceManager.GetString("ResolucionEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolución insertada con éxito.
        /// </summary>
        internal static string ResolucionInsertado {
            get {
                return ResourceManager.GetString("ResolucionInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolución modificada con éxito.
        /// </summary>
        internal static string ResolucionModificado {
            get {
                return ResourceManager.GetString("ResolucionModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen eliminado con éxito.
        /// </summary>
        internal static string ResumenEliminado {
            get {
                return ResourceManager.GetString("ResumenEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen insertado con éxito.
        /// </summary>
        internal static string ResumenInsertado {
            get {
                return ResourceManager.GetString("ResumenInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen modificado con éxito.
        /// </summary>
        internal static string ResumenModificado {
            get {
                return ResourceManager.GetString("ResumenModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol eliminado con éxito.
        /// </summary>
        internal static string RolEliminado {
            get {
                return ResourceManager.GetString("RolEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol insertado con éxito.
        /// </summary>
        internal static string RolInsertado {
            get {
                return ResourceManager.GetString("RolInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol modificado con éxito.
        /// </summary>
        internal static string RolModificado {
            get {
                return ResourceManager.GetString("RolModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de base fue eliminado con exito.
        /// </summary>
        internal static string TipoBaseEliminado {
            get {
                return ResourceManager.GetString("TipoBaseEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de base fue insertado con exito.
        /// </summary>
        internal static string TipoBaseInsertado {
            get {
                return ResourceManager.GetString("TipoBaseInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de base fue modificado con exito.
        /// </summary>
        internal static string TipoBaseModificado {
            get {
                return ResourceManager.GetString("TipoBaseModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de fecha eliminado con éxito.
        /// </summary>
        internal static string TipoFechaEliminado {
            get {
                return ResourceManager.GetString("TipoFechaEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de fecha insertado con éxito.
        /// </summary>
        internal static string TipoFechaInsertado {
            get {
                return ResourceManager.GetString("TipoFechaInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de fecha modificado con éxito.
        /// </summary>
        internal static string TipoFechaModificado {
            get {
                return ResourceManager.GetString("TipoFechaModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de infobol eliminado con éxito.
        /// </summary>
        internal static string TipoInfobolEliminado {
            get {
                return ResourceManager.GetString("TipoInfobolEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de infobol insertado con éxito.
        /// </summary>
        internal static string TipoInfobolInsertado {
            get {
                return ResourceManager.GetString("TipoInfobolInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de infobol modificado con éxito.
        /// </summary>
        internal static string TipoInfobolModificado {
            get {
                return ResourceManager.GetString("TipoInfobolModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta Renovacion no puede ser Eliminada.
        /// </summary>
        internal static string UltimaRenovacion {
            get {
                return ResourceManager.GetString("UltimaRenovacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario eliminado con éxito.
        /// </summary>
        internal static string UsuarioEliminado {
            get {
                return ResourceManager.GetString("UsuarioEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario insertado con éxito.
        /// </summary>
        internal static string UsuarioInsertado {
            get {
                return ResourceManager.GetString("UsuarioInsertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario modificado con éxito.
        /// </summary>
        internal static string UsuarioModificado {
            get {
                return ResourceManager.GetString("UsuarioModificado", resourceCulture);
            }
        }
    }
}
