//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trascend.Bolet.Cliente.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Etiquetas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Etiquetas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trascend.Bolet.Cliente.Recursos.Etiquetas", typeof(Etiquetas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        public static string btnAgregar {
            get {
                return ResourceManager.GetString("btnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditoria.
        /// </summary>
        public static string btnAuditoria {
            get {
                return ResourceManager.GetString("btnAuditoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conectividad.
        /// </summary>
        public static string btnConectividad {
            get {
                return ResourceManager.GetString("btnConectividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string btnConsultar {
            get {
                return ResourceManager.GetString("btnConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string btnContactos {
            get {
                return ResourceManager.GetString("btnContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondencias.
        /// </summary>
        public static string btnCorrespondencias {
            get {
                return ResourceManager.GetString("btnCorrespondencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CXP INT.
        /// </summary>
        public static string btnCXPINT {
            get {
                return ResourceManager.GetString("btnCXPINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desición Comite.
        /// </summary>
        public static string btnDesicionComite {
            get {
                return ResourceManager.GetString("btnDesicionComite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edo. Cta.
        /// </summary>
        public static string btnEdoCta {
            get {
                return ResourceManager.GetString("btnEdoCta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp. Recuperación.
        /// </summary>
        public static string btnExpRecuperacion {
            get {
                return ResourceManager.GetString("btnExpRecuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestiones.
        /// </summary>
        public static string btnGestiones {
            get {
                return ResourceManager.GetString("btnGestiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justificaciones.
        /// </summary>
        public static string btnJustificaciones {
            get {
                return ResourceManager.GetString("btnJustificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        public static string btnModificar {
            get {
                return ResourceManager.GetString("btnModificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDP.
        /// </summary>
        public static string btnNdp {
            get {
                return ResourceManager.GetString("btnNdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Contacto.
        /// </summary>
        public static string btnNuevoContacto {
            get {
                return ResourceManager.GetString("btnNuevoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevos Datos.
        /// </summary>
        public static string btnNuevoDatosCredito {
            get {
                return ResourceManager.GetString("btnNuevoDatosCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Justificación.
        /// </summary>
        public static string btnNuevoJustificacion {
            get {
                return ResourceManager.GetString("btnNuevoJustificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Poder.
        /// </summary>
        public static string btnNuevoPoder {
            get {
                return ResourceManager.GetString("btnNuevoPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        public static string btnQuitar {
            get {
                return ResourceManager.GetString("btnQuitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string btnRegresar {
            get {
                return ResourceManager.GetString("btnRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldos.
        /// </summary>
        public static string btnSaldos {
            get {
                return ResourceManager.GetString("btnSaldos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Transferencia.
        /// </summary>
        public static string btnTrasferencia {
            get {
                return ResourceManager.GetString("btnTrasferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expediente.
        /// </summary>
        public static string btnVerExpediente {
            get {
                return ResourceManager.GetString("btnVerExpediente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Poder.
        /// </summary>
        public static string btnVerPoder {
            get {
                return ResourceManager.GetString("btnVerPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Poderes.
        /// </summary>
        public static string btnVerPoderes {
            get {
                return ResourceManager.GetString("btnVerPoderes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración.
        /// </summary>
        public static string cbiAdministracion {
            get {
                return ResourceManager.GetString("cbiAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración, Marcas y Patentes.
        /// </summary>
        public static string cbiAdministracionMarcasPatentes {
            get {
                return ResourceManager.GetString("cbiAdministracionMarcasPatentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración y Marcas.
        /// </summary>
        public static string cbiAdministracionYMarcas {
            get {
                return ResourceManager.GetString("cbiAdministracionYMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración y Patentes.
        /// </summary>
        public static string cbiAdministracionYPatentes {
            get {
                return ResourceManager.GetString("cbiAdministracionYPatentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFRICA.
        /// </summary>
        public static string cbiAfrica {
            get {
                return ResourceManager.GetString("cbiAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMERICA CENTRAL.
        /// </summary>
        public static string cbiAmericaCentral {
            get {
                return ResourceManager.GetString("cbiAmericaCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMERICA DEL NORTE.
        /// </summary>
        public static string cbiAmericaNorte {
            get {
                return ResourceManager.GetString("cbiAmericaNorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMERICA DEL SUR.
        /// </summary>
        public static string cbiAmericaSur {
            get {
                return ResourceManager.GetString("cbiAmericaSur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASIA.
        /// </summary>
        public static string cbiAsia {
            get {
                return ResourceManager.GetString("cbiAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CARIBE.
        /// </summary>
        public static string cbiCaribe {
            get {
                return ResourceManager.GetString("cbiCaribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casado(a).
        /// </summary>
        public static string cbiCasado {
            get {
                return ResourceManager.GetString("cbiCasado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorciado(a).
        /// </summary>
        public static string cbiDivorciado {
            get {
                return ResourceManager.GetString("cbiDivorciado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUROPA.
        /// </summary>
        public static string cbiEuropa {
            get {
                return ResourceManager.GetString("cbiEuropa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femenino.
        /// </summary>
        public static string cbiFemenino {
            get {
                return ResourceManager.GetString("cbiFemenino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juridica.
        /// </summary>
        public static string cbiJuridica {
            get {
                return ResourceManager.GetString("cbiJuridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string cbiLegal {
            get {
                return ResourceManager.GetString("cbiLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcas.
        /// </summary>
        public static string cbiMarcas {
            get {
                return ResourceManager.GetString("cbiMarcas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcas y Patentes.
        /// </summary>
        public static string cbiMarcasYPatentes {
            get {
                return ResourceManager.GetString("cbiMarcasYPatentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string cbiMasculino {
            get {
                return ResourceManager.GetString("cbiMasculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural.
        /// </summary>
        public static string cbiNatural {
            get {
                return ResourceManager.GetString("cbiNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string cbiNinguno {
            get {
                return ResourceManager.GetString("cbiNinguno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patentes.
        /// </summary>
        public static string cbiPatentes {
            get {
                return ResourceManager.GetString("cbiPatentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sólo Administración.
        /// </summary>
        public static string cbiSoloAdministracion {
            get {
                return ResourceManager.GetString("cbiSoloAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sólo Estado de Cuenta.
        /// </summary>
        public static string cbiSoloEstadoDeCuenta {
            get {
                return ResourceManager.GetString("cbiSoloEstadoDeCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sólo Marcas.
        /// </summary>
        public static string cbiSoloMarca {
            get {
                return ResourceManager.GetString("cbiSoloMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sólo Patentes.
        /// </summary>
        public static string cbiSoloPatente {
            get {
                return ResourceManager.GetString("cbiSoloPatente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soltero(a).
        /// </summary>
        public static string cbiSoltero {
            get {
                return ResourceManager.GetString("cbiSoltero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viudo(a).
        /// </summary>
        public static string cbiViudo {
            get {
                return ResourceManager.GetString("cbiViudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar una fecha.
        /// </summary>
        public static string dpkText {
            get {
                return ResourceManager.GetString("dpkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aba:.
        /// </summary>
        public static string lblAba {
            get {
                return ResourceManager.GetString("lblAba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo:.
        /// </summary>
        public static string lblActivo {
            get {
                return ResourceManager.GetString("lblActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta:.
        /// </summary>
        public static string lblAlerta {
            get {
                return ResourceManager.GetString("lblAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo:.
        /// </summary>
        public static string lblAnexo {
            get {
                return ResourceManager.GetString("lblAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociado:.
        /// </summary>
        public static string lblAsociado {
            get {
                return ResourceManager.GetString("lblAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar:.
        /// </summary>
        public static string lblAutorizar {
            get {
                return ResourceManager.GetString("lblAutorizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco Beneficiario:.
        /// </summary>
        public static string lblBancoBeneficiario {
            get {
                return ResourceManager.GetString("lblBancoBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco Int:.
        /// </summary>
        public static string lblBancoInt {
            get {
                return ResourceManager.GetString("lblBancoInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiario:.
        /// </summary>
        public static string lblBeneficiario {
            get {
                return ResourceManager.GetString("lblBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boletin:.
        /// </summary>
        public static string lblBoletin {
            get {
                return ResourceManager.GetString("lblBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo:.
        /// </summary>
        public static string lblCargo {
            get {
                return ResourceManager.GetString("lblCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta:.
        /// </summary>
        public static string lblCarta {
            get {
                return ResourceManager.GetString("lblCarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCI:.
        /// </summary>
        public static string lblCCI {
            get {
                return ResourceManager.GetString("lblCCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ci:.
        /// </summary>
        public static string lblCi {
            get {
                return ResourceManager.GetString("lblCi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad:.
        /// </summary>
        public static string lblCiudad {
            get {
                return ResourceManager.GetString("lblCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código:.
        /// </summary>
        public static string lblCodigo {
            get {
                return ResourceManager.GetString("lblCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodRes:.
        /// </summary>
        public static string lblCodRes {
            get {
                return ResourceManager.GetString("lblCodRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto:.
        /// </summary>
        public static string lblConcepto {
            get {
                return ResourceManager.GetString("lblConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuyente:.
        /// </summary>
        public static string lblContribuyente {
            get {
                return ResourceManager.GetString("lblContribuyente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporación:.
        /// </summary>
        public static string lblCorporacion {
            get {
                return ResourceManager.GetString("lblCorporacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondencia:.
        /// </summary>
        public static string lblCorrespondencia {
            get {
                return ResourceManager.GetString("lblCorrespondencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta:.
        /// </summary>
        public static string lblCuenta {
            get {
                return ResourceManager.GetString("lblCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento:.
        /// </summary>
        public static string lblDepartamento {
            get {
                return ResourceManager.GetString("lblDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción:.
        /// </summary>
        public static string lblDescripcion {
            get {
                return ResourceManager.GetString("lblDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción (Ingles):.
        /// </summary>
        public static string lblDescripcionIngles {
            get {
                return ResourceManager.GetString("lblDescripcionIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento:.
        /// </summary>
        public static string lblDescuento {
            get {
                return ResourceManager.GetString("lblDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dias:.
        /// </summary>
        public static string lblDias {
            get {
                return ResourceManager.GetString("lblDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día de Crédito:.
        /// </summary>
        public static string lblDiasCredito {
            get {
                return ResourceManager.GetString("lblDiasCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion:.
        /// </summary>
        public static string lblDireccion {
            get {
                return ResourceManager.GetString("lblDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio:.
        /// </summary>
        public static string lblDomicilio {
            get {
                return ResourceManager.GetString("lblDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío Estado de Cuenta:.
        /// </summary>
        public static string lblEdoCuenta {
            get {
                return ResourceManager.GetString("lblEdoCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envío Estado de Cuenta solo digital:.
        /// </summary>
        public static string lblEdoCuentaDigital {
            get {
                return ResourceManager.GetString("lblEdoCuentaDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado:.
        /// </summary>
        public static string lblEstado {
            get {
                return ResourceManager.GetString("lblEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Civil:.
        /// </summary>
        public static string lblEstadoCivil {
            get {
                return ResourceManager.GetString("lblEstadoCivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiqueta:.
        /// </summary>
        public static string lblEtiqueta {
            get {
                return ResourceManager.GetString("lblEtiqueta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturacion:.
        /// </summary>
        public static string lblFacturacion {
            get {
                return ResourceManager.GetString("lblFacturacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facultad:.
        /// </summary>
        public static string lblFacultad {
            get {
                return ResourceManager.GetString("lblFacultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string lblFax {
            get {
                return ResourceManager.GetString("lblFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha:.
        /// </summary>
        public static string lblFecha {
            get {
                return ResourceManager.GetString("lblFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha:.
        /// </summary>
        public static string lblFechaBoletin {
            get {
                return ResourceManager.GetString("lblFechaBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento:.
        /// </summary>
        public static string lblFechaBoletinVence {
            get {
                return ResourceManager.GetString("lblFechaBoletinVence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de impresión:.
        /// </summary>
        public static string lblFechaImpresion {
            get {
                return ResourceManager.GetString("lblFechaImpresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de Pago:.
        /// </summary>
        public static string lblFormaPago {
            get {
                return ResourceManager.GetString("lblFormaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato:.
        /// </summary>
        public static string lblFormato {
            get {
                return ResourceManager.GetString("lblFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcion:.
        /// </summary>
        public static string lblFuncion {
            get {
                return ResourceManager.GetString("lblFuncion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma:.
        /// </summary>
        public static string lblIdioma {
            get {
                return ResourceManager.GetString("lblIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciales:.
        /// </summary>
        public static string lblIniciales {
            get {
                return ResourceManager.GetString("lblIniciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrucciones:.
        /// </summary>
        public static string lblInstrucciones {
            get {
                return ResourceManager.GetString("lblInstrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesado:.
        /// </summary>
        public static string lblInteresado {
            get {
                return ResourceManager.GetString("lblInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, introduzca su Usuario y Contraseña.
        /// </summary>
        public static string lblIntroducirUsuarioYPassword {
            get {
                return ResourceManager.GetString("lblIntroducirUsuarioYPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISF:.
        /// </summary>
        public static string lblIsf {
            get {
                return ResourceManager.GetString("lblIsf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario:.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda:.
        /// </summary>
        public static string lblMoneda {
            get {
                return ResourceManager.GetString("lblMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidad:.
        /// </summary>
        public static string lblNacionalidad {
            get {
                return ResourceManager.GetString("lblNacionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIT:.
        /// </summary>
        public static string lblNit {
            get {
                return ResourceManager.GetString("lblNit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Completo:.
        /// </summary>
        public static string lblNombreCompleto {
            get {
                return ResourceManager.GetString("lblNombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre en español:.
        /// </summary>
        public static string lblNombreEspanol {
            get {
                return ResourceManager.GetString("lblNombreEspanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre en inglés:.
        /// </summary>
        public static string lblNombreIngles {
            get {
                return ResourceManager.GetString("lblNombreIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número:.
        /// </summary>
        public static string lblNumero {
            get {
                return ResourceManager.GetString("lblNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número del Abogado:.
        /// </summary>
        public static string lblNumeroAbogado {
            get {
                return ResourceManager.GetString("lblNumeroAbogado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Impreso Abogado:.
        /// </summary>
        public static string lblNumeroImpresoAbogado {
            get {
                return ResourceManager.GetString("lblNumeroImpresoAbogado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de la Propiedad:.
        /// </summary>
        public static string lblNumeroPropiedad {
            get {
                return ResourceManager.GetString("lblNumeroPropiedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº del Poder:.
        /// </summary>
        public static string lblNumPoder {
            get {
                return ResourceManager.GetString("lblNumPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones:.
        /// </summary>
        public static string lblObservaciones {
            get {
                return ResourceManager.GetString("lblObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagina:.
        /// </summary>
        public static string lblPagina {
            get {
                return ResourceManager.GetString("lblPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais:.
        /// </summary>
        public static string lblPais {
            get {
                return ResourceManager.GetString("lblPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente con Statement:.
        /// </summary>
        public static string lblPendienteStatement {
            get {
                return ResourceManager.GetString("lblPendienteStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por Vencer:.
        /// </summary>
        public static string lblPorVencer {
            get {
                return ResourceManager.GetString("lblPorVencer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximo Evento:.
        /// </summary>
        public static string lblProximoPaso {
            get {
                return ResourceManager.GetString("lblProximoPaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximo Evento (Ingles):.
        /// </summary>
        public static string lblProximoPasoIngles {
            get {
                return ResourceManager.GetString("lblProximoPasoIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        public static string lblRegion {
            get {
                return ResourceManager.GetString("lblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. Mercantil:.
        /// </summary>
        public static string lblRegMercantil {
            get {
                return ResourceManager.GetString("lblRegMercantil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIF:.
        /// </summary>
        public static string lblRif {
            get {
                return ResourceManager.GetString("lblRif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R. Mercantil:.
        /// </summary>
        public static string lblRMercantil {
            get {
                return ResourceManager.GetString("lblRMercantil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol:.
        /// </summary>
        public static string lblRol {
            get {
                return ResourceManager.GetString("lblRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string lblSalir {
            get {
                return ResourceManager.GetString("lblSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimiento:.
        /// </summary>
        public static string lblSeguimiento {
            get {
                return ResourceManager.GetString("lblSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género:.
        /// </summary>
        public static string lblSexo {
            get {
                return ResourceManager.GetString("lblSexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swif:.
        /// </summary>
        public static string lblSwif {
            get {
                return ResourceManager.GetString("lblSwif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swif Int:.
        /// </summary>
        public static string lblSwifInt {
            get {
                return ResourceManager.GetString("lblSwifInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swift Int:.
        /// </summary>
        public static string lblSwiftInt {
            get {
                return ResourceManager.GetString("lblSwiftInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifas:.
        /// </summary>
        public static string lblTarifas {
            get {
                return ResourceManager.GetString("lblTarifas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono:.
        /// </summary>
        public static string lblTelefono {
            get {
                return ResourceManager.GetString("lblTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Cliente:.
        /// </summary>
        public static string lblTipoCliente {
            get {
                return ResourceManager.GetString("lblTipoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de persona:.
        /// </summary>
        public static string lblTipoPersona {
            get {
                return ResourceManager.GetString("lblTipoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso:.
        /// </summary>
        public static string lblUso {
            get {
                return ResourceManager.GetString("lblUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vencido a:.
        /// </summary>
        public static string lblVencidoA {
            get {
                return ResourceManager.GetString("lblVencidoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumen:.
        /// </summary>
        public static string lblVolumen {
            get {
                return ResourceManager.GetString("lblVolumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web:.
        /// </summary>
        public static string lblWeb {
            get {
                return ResourceManager.GetString("lblWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociado.
        /// </summary>
        public static string lsvAsociado {
            get {
                return ResourceManager.GetString("lsvAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco Beneficiario.
        /// </summary>
        public static string lsvBancoBeneficiario {
            get {
                return ResourceManager.GetString("lsvBancoBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiario.
        /// </summary>
        public static string lsvBeneficiario {
            get {
                return ResourceManager.GetString("lsvBeneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta.
        /// </summary>
        public static string lsvCarta {
            get {
                return ResourceManager.GetString("lsvCarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string lsvCodigo {
            get {
                return ResourceManager.GetString("lsvCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodRes.
        /// </summary>
        public static string lsvCodRes {
            get {
                return ResourceManager.GetString("lsvCodRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto.
        /// </summary>
        public static string lsvConcepto {
            get {
                return ResourceManager.GetString("lsvConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta.
        /// </summary>
        public static string lsvCuenta {
            get {
                return ResourceManager.GetString("lsvCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string lsvDescripcion {
            get {
                return ResourceManager.GetString("lsvDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción (Ingles).
        /// </summary>
        public static string lsvDescripcionIngles {
            get {
                return ResourceManager.GetString("lsvDescripcionIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio.
        /// </summary>
        public static string lsvDomicilio {
            get {
                return ResourceManager.GetString("lsvDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lsvEmail {
            get {
                return ResourceManager.GetString("lsvEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facultad.
        /// </summary>
        public static string lsvFacultad {
            get {
                return ResourceManager.GetString("lsvFacultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string lsvFax {
            get {
                return ResourceManager.GetString("lsvFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string lsvFecha {
            get {
                return ResourceManager.GetString("lsvFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string lsvFechaBoletin {
            get {
                return ResourceManager.GetString("lsvFechaBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de vencimiento.
        /// </summary>
        public static string lsvFechaBoletinVence {
            get {
                return ResourceManager.GetString("lsvFechaBoletinVence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de impresion.
        /// </summary>
        public static string lsvFechaImpresion {
            get {
                return ResourceManager.GetString("lsvFechaImpresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato.
        /// </summary>
        public static string lsvFormato {
            get {
                return ResourceManager.GetString("lsvFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string lsvId {
            get {
                return ResourceManager.GetString("lsvId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id del Boletin.
        /// </summary>
        public static string lsvIdBoletin {
            get {
                return ResourceManager.GetString("lsvIdBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidad.
        /// </summary>
        public static string lsvNacionalidad {
            get {
                return ResourceManager.GetString("lsvNacionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lsvNombre {
            get {
                return ResourceManager.GetString("lsvNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº del Poder.
        /// </summary>
        public static string lsvNumPoder {
            get {
                return ResourceManager.GetString("lsvNumPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacion.
        /// </summary>
        public static string lsvOperacion {
            get {
                return ResourceManager.GetString("lsvOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximo Evento.
        /// </summary>
        public static string lsvProximoPaso {
            get {
                return ResourceManager.GetString("lsvProximoPaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximo Evento (Ingles).
        /// </summary>
        public static string lsvProximoPasoIngles {
            get {
                return ResourceManager.GetString("lsvProximoPasoIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string lsvRegion {
            get {
                return ResourceManager.GetString("lsvRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimiento.
        /// </summary>
        public static string lsvSeguimiento {
            get {
                return ResourceManager.GetString("lsvSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string lsvTelefono {
            get {
                return ResourceManager.GetString("lsvTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string lsvUsuario {
            get {
                return ResourceManager.GetString("lsvUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agente.
        /// </summary>
        public static string menuItemAgente {
            get {
                return ResourceManager.GetString("menuItemAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string menuItemAgregar {
            get {
                return ResourceManager.GetString("menuItemAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo.
        /// </summary>
        public static string menuItemAnexo {
            get {
                return ResourceManager.GetString("menuItemAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Archivo.
        /// </summary>
        public static string menuItemArchivo {
            get {
                return ResourceManager.GetString("menuItemArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociado.
        /// </summary>
        public static string menuItemAsociado {
            get {
                return ResourceManager.GetString("menuItemAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayuda.
        /// </summary>
        public static string menuItemAyuda {
            get {
                return ResourceManager.GetString("menuItemAyuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        public static string menuItemAyudaAcerca {
            get {
                return ResourceManager.GetString("menuItemAyudaAcerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boletin.
        /// </summary>
        public static string menuItemBoletin {
            get {
                return ResourceManager.GetString("menuItemBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        public static string menuItemConsultar {
            get {
                return ResourceManager.GetString("menuItemConsultar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        public static string menuItemCopiar {
            get {
                return ResourceManager.GetString("menuItemCopiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correspondencia.
        /// </summary>
        public static string menuItemCorrespondencia {
            get {
                return ResourceManager.GetString("menuItemCorrespondencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortar.
        /// </summary>
        public static string menuItemCortar {
            get {
                return ResourceManager.GetString("menuItemCortar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Editar.
        /// </summary>
        public static string menuItemEditar {
            get {
                return ResourceManager.GetString("menuItemEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string menuItemEstado {
            get {
                return ResourceManager.GetString("menuItemEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estatus.
        /// </summary>
        public static string menuItemEstatus {
            get {
                return ResourceManager.GetString("menuItemEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Objetos por Roles.
        /// </summary>
        public static string menuItemGestionarObjetosXRoles {
            get {
                return ResourceManager.GetString("menuItemGestionarObjetosXRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Poderes con Agentes.
        /// </summary>
        public static string menuItemGestionarPoderesXAgentes {
            get {
                return ResourceManager.GetString("menuItemGestionarPoderesXAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string menuItemHistoria {
            get {
                return ResourceManager.GetString("menuItemHistoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesado.
        /// </summary>
        public static string menuItemInteresado {
            get {
                return ResourceManager.GetString("menuItemInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase Internacional.
        /// </summary>
        public static string menuItemInternacional {
            get {
                return ResourceManager.GetString("menuItemInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio.
        /// </summary>
        public static string menuItemMedio {
            get {
                return ResourceManager.GetString("menuItemMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clase Nacional.
        /// </summary>
        public static string menuItemNacional {
            get {
                return ResourceManager.GetString("menuItemNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto.
        /// </summary>
        public static string menuItemObjetivo {
            get {
                return ResourceManager.GetString("menuItemObjetivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string menuItemPais {
            get {
                return ResourceManager.GetString("menuItemPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pegar.
        /// </summary>
        public static string menuItemPegar {
            get {
                return ResourceManager.GetString("menuItemPegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poder.
        /// </summary>
        public static string menuItemPoder {
            get {
                return ResourceManager.GetString("menuItemPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolución.
        /// </summary>
        public static string menuItemResolucion {
            get {
                return ResourceManager.GetString("menuItemResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string menuItemResumen {
            get {
                return ResourceManager.GetString("menuItemResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string menuItemRol {
            get {
                return ResourceManager.GetString("menuItemRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        public static string menuItemSalir {
            get {
                return ResourceManager.GetString("menuItemSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Fecha.
        /// </summary>
        public static string menuItemTipoFecha {
            get {
                return ResourceManager.GetString("menuItemTipoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Infobol.
        /// </summary>
        public static string menuItemTipoInfobol {
            get {
                return ResourceManager.GetString("menuItemTipoInfobol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string menuItemUsuario {
            get {
                return ResourceManager.GetString("menuItemUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Agente.
        /// </summary>
        public static string titleAgregarAgente {
            get {
                return ResourceManager.GetString("titleAgregarAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Anexo.
        /// </summary>
        public static string titleAgregarAnexo {
            get {
                return ResourceManager.GetString("titleAgregarAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Asociado.
        /// </summary>
        public static string titleAgregarAsociado {
            get {
                return ResourceManager.GetString("titleAgregarAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Boletin.
        /// </summary>
        public static string titleAgregarBoletin {
            get {
                return ResourceManager.GetString("titleAgregarBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Contacto.
        /// </summary>
        public static string titleAgregarContacto {
            get {
                return ResourceManager.GetString("titleAgregarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Datos de Transferencia.
        /// </summary>
        public static string titleAgregarDatosTransferencia {
            get {
                return ResourceManager.GetString("titleAgregarDatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Estado.
        /// </summary>
        public static string titleAgregarEstado {
            get {
                return ResourceManager.GetString("titleAgregarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Estatus.
        /// </summary>
        public static string titleAgregarEstatus {
            get {
                return ResourceManager.GetString("titleAgregarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Interesado.
        /// </summary>
        public static string titleAgregarInteresado {
            get {
                return ResourceManager.GetString("titleAgregarInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Clase Internacional.
        /// </summary>
        public static string titleAgregarInternacional {
            get {
                return ResourceManager.GetString("titleAgregarInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgregarJustificación.
        /// </summary>
        public static string titleAgregarJustificacion {
            get {
                return ResourceManager.GetString("titleAgregarJustificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Medio.
        /// </summary>
        public static string titleAgregarMedio {
            get {
                return ResourceManager.GetString("titleAgregarMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Clase Nacional.
        /// </summary>
        public static string titleAgregarNacional {
            get {
                return ResourceManager.GetString("titleAgregarNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Objeto.
        /// </summary>
        public static string titleAgregarObjeto {
            get {
                return ResourceManager.GetString("titleAgregarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Pais.
        /// </summary>
        public static string titleAgregarPais {
            get {
                return ResourceManager.GetString("titleAgregarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Poder.
        /// </summary>
        public static string titleAgregarPoder {
            get {
                return ResourceManager.GetString("titleAgregarPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Resolucion.
        /// </summary>
        public static string titleAgregarResolucion {
            get {
                return ResourceManager.GetString("titleAgregarResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Resumen.
        /// </summary>
        public static string titleAgregarResumen {
            get {
                return ResourceManager.GetString("titleAgregarResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Rol.
        /// </summary>
        public static string titleAgregarRol {
            get {
                return ResourceManager.GetString("titleAgregarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Tipo de Fecha.
        /// </summary>
        public static string titleAgregarTipoFecha {
            get {
                return ResourceManager.GetString("titleAgregarTipoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Tipo de Infobol.
        /// </summary>
        public static string titleAgregarTipoInfobol {
            get {
                return ResourceManager.GetString("titleAgregarTipoInfobol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Usuario.
        /// </summary>
        public static string titleAgregarUsuario {
            get {
                return ResourceManager.GetString("titleAgregarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Agente.
        /// </summary>
        public static string titleConsultarAgente {
            get {
                return ResourceManager.GetString("titleConsultarAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Agentes.
        /// </summary>
        public static string titleConsultarAgentes {
            get {
                return ResourceManager.GetString("titleConsultarAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo.
        /// </summary>
        public static string titleConsultarAnexo {
            get {
                return ResourceManager.GetString("titleConsultarAnexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Anexos.
        /// </summary>
        public static string titleConsultarAnexos {
            get {
                return ResourceManager.GetString("titleConsultarAnexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Asociado.
        /// </summary>
        public static string titleConsultarAsociado {
            get {
                return ResourceManager.GetString("titleConsultarAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Asociados.
        /// </summary>
        public static string titleConsultarAsociados {
            get {
                return ResourceManager.GetString("titleConsultarAsociados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Boletin.
        /// </summary>
        public static string titleConsultarBoletin {
            get {
                return ResourceManager.GetString("titleConsultarBoletin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Boletines.
        /// </summary>
        public static string titleConsultarBoletines {
            get {
                return ResourceManager.GetString("titleConsultarBoletines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Contacto.
        /// </summary>
        public static string titleConsultarContacto {
            get {
                return ResourceManager.GetString("titleConsultarContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Datos de Transferencia.
        /// </summary>
        public static string titleConsultarDatosTransferencia {
            get {
                return ResourceManager.GetString("titleConsultarDatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Estado.
        /// </summary>
        public static string titleConsultarEstado {
            get {
                return ResourceManager.GetString("titleConsultarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Estados.
        /// </summary>
        public static string titleConsultarEstados {
            get {
                return ResourceManager.GetString("titleConsultarEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Estatus.
        /// </summary>
        public static string titleConsultarEstatus {
            get {
                return ResourceManager.GetString("titleConsultarEstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Estatus.
        /// </summary>
        public static string titleConsultarEstatuses {
            get {
                return ResourceManager.GetString("titleConsultarEstatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Interesado.
        /// </summary>
        public static string titleConsultarInteresado {
            get {
                return ResourceManager.GetString("titleConsultarInteresado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Interesados.
        /// </summary>
        public static string titleConsultarInteresados {
            get {
                return ResourceManager.GetString("titleConsultarInteresados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Clase Internacional.
        /// </summary>
        public static string titleConsultarInternacional {
            get {
                return ResourceManager.GetString("titleConsultarInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Clases Internacionales.
        /// </summary>
        public static string titleConsultarInternacionales {
            get {
                return ResourceManager.GetString("titleConsultarInternacionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Justificación.
        /// </summary>
        public static string titleConsultarJustificacion {
            get {
                return ResourceManager.GetString("titleConsultarJustificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Medio.
        /// </summary>
        public static string titleConsultarMedio {
            get {
                return ResourceManager.GetString("titleConsultarMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Medios.
        /// </summary>
        public static string titleConsultarMedios {
            get {
                return ResourceManager.GetString("titleConsultarMedios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Clase Nacional.
        /// </summary>
        public static string titleConsultarNacional {
            get {
                return ResourceManager.GetString("titleConsultarNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Clases Nacionales.
        /// </summary>
        public static string titleConsultarNacionales {
            get {
                return ResourceManager.GetString("titleConsultarNacionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Objeto.
        /// </summary>
        public static string titleConsultarObjeto {
            get {
                return ResourceManager.GetString("titleConsultarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Objetos.
        /// </summary>
        public static string titleConsultarObjetos {
            get {
                return ResourceManager.GetString("titleConsultarObjetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Pais.
        /// </summary>
        public static string titleConsultarPais {
            get {
                return ResourceManager.GetString("titleConsultarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Paises.
        /// </summary>
        public static string titleConsultarPaises {
            get {
                return ResourceManager.GetString("titleConsultarPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Poder.
        /// </summary>
        public static string titleConsultarPoder {
            get {
                return ResourceManager.GetString("titleConsultarPoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Poderes.
        /// </summary>
        public static string titleConsultarPoderes {
            get {
                return ResourceManager.GetString("titleConsultarPoderes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Resolucion.
        /// </summary>
        public static string titleConsultarResolucion {
            get {
                return ResourceManager.GetString("titleConsultarResolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Resoluciones.
        /// </summary>
        public static string titleConsultarResoluciones {
            get {
                return ResourceManager.GetString("titleConsultarResoluciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Resumen.
        /// </summary>
        public static string titleConsultarResumen {
            get {
                return ResourceManager.GetString("titleConsultarResumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Resumenes.
        /// </summary>
        public static string titleConsultarResumenes {
            get {
                return ResourceManager.GetString("titleConsultarResumenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Rol.
        /// </summary>
        public static string titleConsultarRol {
            get {
                return ResourceManager.GetString("titleConsultarRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Roles.
        /// </summary>
        public static string titleConsultarRoles {
            get {
                return ResourceManager.GetString("titleConsultarRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Tipo de Fecha.
        /// </summary>
        public static string titleConsultarTipoFecha {
            get {
                return ResourceManager.GetString("titleConsultarTipoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Tipos de Fechas.
        /// </summary>
        public static string titleConsultarTipoFechas {
            get {
                return ResourceManager.GetString("titleConsultarTipoFechas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Tipo de Infobol.
        /// </summary>
        public static string titleConsultarTipoInfobol {
            get {
                return ResourceManager.GetString("titleConsultarTipoInfobol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Tipos de Infoboles.
        /// </summary>
        public static string titleConsultarTipoInfoboles {
            get {
                return ResourceManager.GetString("titleConsultarTipoInfoboles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Usuario.
        /// </summary>
        public static string titleConsultarUsuario {
            get {
                return ResourceManager.GetString("titleConsultarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Usuarios.
        /// </summary>
        public static string titleConsultarUsuarios {
            get {
                return ResourceManager.GetString("titleConsultarUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Relacion Objeto con Rol.
        /// </summary>
        public static string titleGestionarObjeto {
            get {
                return ResourceManager.GetString("titleGestionarObjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar objetos por roles.
        /// </summary>
        public static string titleGestionarObjetosXRoles {
            get {
                return ResourceManager.GetString("titleGestionarObjetosXRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestionar Relacion de Poderes con Agentes.
        /// </summary>
        public static string titleGestionarPoderesXAgentes {
            get {
                return ResourceManager.GetString("titleGestionarPoderesXAgentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Auditorias.
        /// </summary>
        public static string titleListaAuditorias {
            get {
                return ResourceManager.GetString("titleListaAuditorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        public static string titleListaContactos {
            get {
                return ResourceManager.GetString("titleListaContactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Datos de Transferencia.
        /// </summary>
        public static string titleListaDatosTransferencia {
            get {
                return ResourceManager.GetString("titleListaDatosTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Justificaciones.
        /// </summary>
        public static string titleListaJustificaciones {
            get {
                return ResourceManager.GetString("titleListaJustificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Poderes.
        /// </summary>
        public static string titleListaPoderes {
            get {
                return ResourceManager.GetString("titleListaPoderes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolet &amp; Terrero.
        /// </summary>
        public static string titleLogin {
            get {
                return ResourceManager.GetString("titleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string titlePaginaPrincipal {
            get {
                return ResourceManager.GetString("titlePaginaPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolet &amp; Terrero.
        /// </summary>
        public static string titlePrincipal {
            get {
                return ResourceManager.GetString("titlePrincipal", resourceCulture);
            }
        }
    }
}
