'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.1
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Recursos
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Ids
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Diginsoft.Bolet.Cliente.Fac.Ids", GetType(Ids).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTAGENTE.
        '''</summary>
        Public Shared ReadOnly Property Agente() As String
            Get
                Return ResourceManager.GetString("Agente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTAGENTE.
        '''</summary>
        Public Shared ReadOnly Property AgregarAgente() As String
            Get
                Return ResourceManager.GetString("AgregarAgente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ASOCIADOS.
        '''</summary>
        Public Shared ReadOnly Property AgregarAsociado() As String
            Get
                Return ResourceManager.GetString("AgregarAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTBOLETIN.
        '''</summary>
        Public Shared ReadOnly Property AgregarBoletin() As String
            Get
                Return ResourceManager.GetString("AgregarBoletin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_ESTADOS.
        '''</summary>
        Public Shared ReadOnly Property AgregarEstado() As String
            Get
                Return ResourceManager.GetString("AgregarEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TESTADOS.
        '''</summary>
        Public Shared ReadOnly Property AgregarEstatus() As String
            Get
                Return ResourceManager.GetString("AgregarEstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_INTERESADOS.
        '''</summary>
        Public Shared ReadOnly Property AgregarInteresado() As String
            Get
                Return ResourceManager.GetString("AgregarInteresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTINT.
        '''</summary>
        Public Shared ReadOnly Property AgregarInternacional() As String
            Get
                Return ResourceManager.GetString("AgregarInternacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CONJUST.
        '''</summary>
        Public Shared ReadOnly Property AgregarJustificacion() As String
            Get
                Return ResourceManager.GetString("AgregarJustificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTNAC.
        '''</summary>
        Public Shared ReadOnly Property AgregarNacional() As String
            Get
                Return ResourceManager.GetString("AgregarNacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTOBJ.
        '''</summary>
        Public Shared ReadOnly Property AgregarObjeto() As String
            Get
                Return ResourceManager.GetString("AgregarObjeto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PAISES.
        '''</summary>
        Public Shared ReadOnly Property AgregarPais() As String
            Get
                Return ResourceManager.GetString("AgregarPais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PODERES.
        '''</summary>
        Public Shared ReadOnly Property AgregarPoder() As String
            Get
                Return ResourceManager.GetString("AgregarPoder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_RESOLBOL.
        '''</summary>
        Public Shared ReadOnly Property AgregarResolucion() As String
            Get
                Return ResourceManager.GetString("AgregarResolucion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGMROL.
        '''</summary>
        Public Shared ReadOnly Property AgregarRol() As String
            Get
                Return ResourceManager.GetString("AgregarRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TASAS.
        '''</summary>
        Public Shared ReadOnly Property AgregarTasa() As String
            Get
                Return ResourceManager.GetString("AgregarTasa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TFECHAS.
        '''</summary>
        Public Shared ReadOnly Property AgregarTipoFecha() As String
            Get
                Return ResourceManager.GetString("AgregarTipoFecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TINFOBOL.
        '''</summary>
        Public Shared ReadOnly Property AgregarTipoInfobol() As String
            Get
                Return ResourceManager.GetString("AgregarTipoInfobol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTUSU.
        '''</summary>
        Public Shared ReadOnly Property AgregarUsuario() As String
            Get
                Return ResourceManager.GetString("AgregarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ASOCIADOS.
        '''</summary>
        Public Shared ReadOnly Property Asociado() As String
            Get
                Return ResourceManager.GetString("Asociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTBOLETIN.
        '''</summary>
        Public Shared ReadOnly Property Boletin() As String
            Get
                Return ResourceManager.GetString("Boletin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTAGENTE.
        '''</summary>
        Public Shared ReadOnly Property ConsultarAgente() As String
            Get
                Return ResourceManager.GetString("ConsultarAgente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTAGENTE.
        '''</summary>
        Public Shared ReadOnly Property ConsultarAgentes() As String
            Get
                Return ResourceManager.GetString("ConsultarAgentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ASOCIADOS.
        '''</summary>
        Public Shared ReadOnly Property ConsultarAsociado() As String
            Get
                Return ResourceManager.GetString("ConsultarAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ASOCIADOS.
        '''</summary>
        Public Shared ReadOnly Property ConsultarAsociados() As String
            Get
                Return ResourceManager.GetString("ConsultarAsociados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTBOLETIN.
        '''</summary>
        Public Shared ReadOnly Property ConsultarBoletin() As String
            Get
                Return ResourceManager.GetString("ConsultarBoletin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CONTACTOS.
        '''</summary>
        Public Shared ReadOnly Property ConsultarContacto() As String
            Get
                Return ResourceManager.GetString("ConsultarContacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_ESTADOS.
        '''</summary>
        Public Shared ReadOnly Property ConsultarEstado() As String
            Get
                Return ResourceManager.GetString("ConsultarEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TESTADOS.
        '''</summary>
        Public Shared ReadOnly Property ConsultarEstatus() As String
            Get
                Return ResourceManager.GetString("ConsultarEstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TESTADOS.
        '''</summary>
        Public Shared ReadOnly Property ConsultarEstatuses() As String
            Get
                Return ResourceManager.GetString("ConsultarEstatuses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_INTERESADOS.
        '''</summary>
        Public Shared ReadOnly Property ConsultarInteresado() As String
            Get
                Return ResourceManager.GetString("ConsultarInteresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTINT.
        '''</summary>
        Public Shared ReadOnly Property ConsultarInternacional() As String
            Get
                Return ResourceManager.GetString("ConsultarInternacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTINT.
        '''</summary>
        Public Shared ReadOnly Property ConsultarInternacionales() As String
            Get
                Return ResourceManager.GetString("ConsultarInternacionales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ASO_JUST.
        '''</summary>
        Public Shared ReadOnly Property ConsultarJustificaciones() As String
            Get
                Return ResourceManager.GetString("ConsultarJustificaciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTNAC.
        '''</summary>
        Public Shared ReadOnly Property ConsultarNacional() As String
            Get
                Return ResourceManager.GetString("ConsultarNacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTNAC.
        '''</summary>
        Public Shared ReadOnly Property ConsultarNacionales() As String
            Get
                Return ResourceManager.GetString("ConsultarNacionales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTOBJ.
        '''</summary>
        Public Shared ReadOnly Property ConsultarObjeto() As String
            Get
                Return ResourceManager.GetString("ConsultarObjeto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTOBJ.
        '''</summary>
        Public Shared ReadOnly Property ConsultarObjetos() As String
            Get
                Return ResourceManager.GetString("ConsultarObjetos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PAISES.
        '''</summary>
        Public Shared ReadOnly Property ConsultarPais() As String
            Get
                Return ResourceManager.GetString("ConsultarPais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PAISES.
        '''</summary>
        Public Shared ReadOnly Property ConsultarPaises() As String
            Get
                Return ResourceManager.GetString("ConsultarPaises", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PODERES.
        '''</summary>
        Public Shared ReadOnly Property ConsultarPoder() As String
            Get
                Return ResourceManager.GetString("ConsultarPoder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PODERES.
        '''</summary>
        Public Shared ReadOnly Property ConsultarPoderes() As String
            Get
                Return ResourceManager.GetString("ConsultarPoderes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_RESOLBOL.
        '''</summary>
        Public Shared ReadOnly Property ConsultarResolucion() As String
            Get
                Return ResourceManager.GetString("ConsultarResolucion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_RESOLBOL.
        '''</summary>
        Public Shared ReadOnly Property ConsultarResoluciones() As String
            Get
                Return ResourceManager.GetString("ConsultarResoluciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGMROL.
        '''</summary>
        Public Shared ReadOnly Property ConsultarRol() As String
            Get
                Return ResourceManager.GetString("ConsultarRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGMROL.
        '''</summary>
        Public Shared ReadOnly Property ConsultarRoles() As String
            Get
                Return ResourceManager.GetString("ConsultarRoles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TFECHAS.
        '''</summary>
        Public Shared ReadOnly Property ConsultarTipoFecha() As String
            Get
                Return ResourceManager.GetString("ConsultarTipoFecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TFECHAS.
        '''</summary>
        Public Shared ReadOnly Property ConsultarTipoFechas() As String
            Get
                Return ResourceManager.GetString("ConsultarTipoFechas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TINFOBOL.
        '''</summary>
        Public Shared ReadOnly Property ConsultarTipoInfobol() As String
            Get
                Return ResourceManager.GetString("ConsultarTipoInfobol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TINFOBOL.
        '''</summary>
        Public Shared ReadOnly Property ConsultarTipoInfoboles() As String
            Get
                Return ResourceManager.GetString("ConsultarTipoInfoboles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTUSU.
        '''</summary>
        Public Shared ReadOnly Property ConsultarUsuario() As String
            Get
                Return ResourceManager.GetString("ConsultarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTUSU.
        '''</summary>
        Public Shared ReadOnly Property ConsultarUsuarios() As String
            Get
                Return ResourceManager.GetString("ConsultarUsuarios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CONTACTOS.
        '''</summary>
        Public Shared ReadOnly Property Contacto() As String
            Get
                Return ResourceManager.GetString("Contacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ASOCIADOS.
        '''</summary>
        Public Shared ReadOnly Property EliminarAsociado() As String
            Get
                Return ResourceManager.GetString("EliminarAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTBOLETIN.
        '''</summary>
        Public Shared ReadOnly Property EliminarBoletin() As String
            Get
                Return ResourceManager.GetString("EliminarBoletin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_ESTADOS.
        '''</summary>
        Public Shared ReadOnly Property EliminarEstado() As String
            Get
                Return ResourceManager.GetString("EliminarEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TESTADOS.
        '''</summary>
        Public Shared ReadOnly Property EliminarEstatus() As String
            Get
                Return ResourceManager.GetString("EliminarEstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TFECHAS.
        '''</summary>
        Public Shared ReadOnly Property EliminarFecha() As String
            Get
                Return ResourceManager.GetString("EliminarFecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_INTERESADOS.
        '''</summary>
        Public Shared ReadOnly Property EliminarInteresado() As String
            Get
                Return ResourceManager.GetString("EliminarInteresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTINT.
        '''</summary>
        Public Shared ReadOnly Property EliminarInternacional() As String
            Get
                Return ResourceManager.GetString("EliminarInternacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTNAC.
        '''</summary>
        Public Shared ReadOnly Property EliminarNacional() As String
            Get
                Return ResourceManager.GetString("EliminarNacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTOBJ.
        '''</summary>
        Public Shared ReadOnly Property EliminarObjeto() As String
            Get
                Return ResourceManager.GetString("EliminarObjeto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PAISES.
        '''</summary>
        Public Shared ReadOnly Property EliminarPais() As String
            Get
                Return ResourceManager.GetString("EliminarPais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PODERES.
        '''</summary>
        Public Shared ReadOnly Property EliminarPoder() As String
            Get
                Return ResourceManager.GetString("EliminarPoder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_RESOLBOL.
        '''</summary>
        Public Shared ReadOnly Property EliminarResolucion() As String
            Get
                Return ResourceManager.GetString("EliminarResolucion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGMROL.
        '''</summary>
        Public Shared ReadOnly Property EliminarRol() As String
            Get
                Return ResourceManager.GetString("EliminarRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TINFOBOL.
        '''</summary>
        Public Shared ReadOnly Property EliminarTipoInfobol() As String
            Get
                Return ResourceManager.GetString("EliminarTipoInfobol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTUSU.
        '''</summary>
        Public Shared ReadOnly Property EliminarUsuario() As String
            Get
                Return ResourceManager.GetString("EliminarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_ESTADOS.
        '''</summary>
        Public Shared ReadOnly Property Estado() As String
            Get
                Return ResourceManager.GetString("Estado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TESTADOS.
        '''</summary>
        Public Shared ReadOnly Property Estatus() As String
            Get
                Return ResourceManager.GetString("Estatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TANUALIDAD.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarAnualidad() As String
            Get
                Return ResourceManager.GetString("fac_AgregarAnualidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CH_REC.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarChequeRecido() As String
            Get
                Return ResourceManager.GetString("fac_AgregarChequeRecido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CPTO_GES.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarConceptoGestion() As String
            Get
                Return ResourceManager.GetString("fac_AgregarConceptoGestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a COR_MAIL_IN.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarCorrespondencia() As String
            Get
                Return ResourceManager.GetString("fac_AgregarCorrespondencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DPTO_SERV.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarDepartamentoServicio() As String
            Get
                Return ResourceManager.GetString("fac_AgregarDepartamentoServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_SERV_DESG.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarDesgloseServicio() As String
            Get
                Return ResourceManager.GetString("fac_AgregarDesgloseServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DET_ENV.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarDetalleEnvio() As String
            Get
                Return ResourceManager.GetString("fac_AgregarDetalleEnvio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DET_PG.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarDetallePago() As String
            Get
                Return ResourceManager.GetString("fac_AgregarDetallePago", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TDOC_MARCA.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarDocumentosMarca() As String
            Get
                Return ResourceManager.GetString("fac_AgregarDocumentosMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TDOC_PATENTE.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarDocumentosPatente() As String
            Get
                Return ResourceManager.GetString("fac_AgregarDocumentosPatente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TDOC_TRADUCC.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarDocumentosTraduccion() As String
            Get
                Return ResourceManager.GetString("fac_AgregarDocumentosTraduccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ETI_FAC.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarEtiqueta() As String
            Get
                Return ResourceManager.GetString("fac_AgregarEtiqueta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_COBROS.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacCobro() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacCobro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CREDITOS.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacCredito() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacCredito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DETALLES_ANU.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacFactuDetaAnulada() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacFactuDetaAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DETALLES_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacFactuDetaProforma() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacFactuDetaProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_FACTURAS.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacFactura() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacFactura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ANUL.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacFacturaAnulada() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacFacturaAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_FACTURAS_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacFacturaProforma() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacFacturaProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GESTIONES.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacGestion() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacGestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CONJUST.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacJustificacion() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacJustificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACIONES_ANU.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacOperacionAnulada() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacOperacionAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_ANU.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacOperacionDetaAnulada() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacOperacionDetaAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacOperacionDetalle() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacOperacionDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_TM.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacOperacionDetalleTm() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacOperacionDetalleTm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacOperacionDetaProforma() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacOperacionDetaProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_TM_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacOperacionDetaTmProforma() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacOperacionDetaTmProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACIONES_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacOperacionProforma() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacOperacionProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CXP_BOL.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacPagoBolivia() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacPagoBolivia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TRECURSO.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarFacRecurso() As String
            Get
                Return ResourceManager.GetString("fac_AgregarFacRecurso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GUIAS.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarGuia() As String
            Get
                Return ResourceManager.GetString("fac_AgregarGuia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_IMPUESTOS.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarImpuesto() As String
            Get
                Return ResourceManager.GetString("fac_AgregarImpuesto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TMATERIAL.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarMaterial() As String
            Get
                Return ResourceManager.GetString("fac_AgregarMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_MEDIO_GES.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarMediosGestion() As String
            Get
                Return ResourceManager.GetString("fac_AgregarMediosGestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_MOTIVO.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarMotivo() As String
            Get
                Return ResourceManager.GetString("fac_AgregarMotivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_SOCIEDAD.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarSociedad() As String
            Get
                Return ResourceManager.GetString("fac_AgregarSociedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TARIFAS_SERV.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarTarifaServicio() As String
            Get
                Return ResourceManager.GetString("fac_AgregarTarifaServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TASAS.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarTasa() As String
            Get
                Return ResourceManager.GetString("fac_AgregarTasa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TIPO_CLASE.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarTipoClase() As String
            Get
                Return ResourceManager.GetString("fac_AgregarTipoClase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TIPO_MARCA.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarTipoMarca() As String
            Get
                Return ResourceManager.GetString("fac_AgregarTipoMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TIPO_PATENTE.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarTipoPatente() As String
            Get
                Return ResourceManager.GetString("fac_AgregarTipoPatente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GESTIONES_CG.
        '''</summary>
        Public Shared ReadOnly Property fac_AgregarViGestionAsociado() As String
            Get
                Return ResourceManager.GetString("fac_AgregarViGestionAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CH_REC.
        '''</summary>
        Public Shared ReadOnly Property fac_ChequeRecido() As String
            Get
                Return ResourceManager.GetString("fac_ChequeRecido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CPTO_GES.
        '''</summary>
        Public Shared ReadOnly Property fac_ConceptoGestion() As String
            Get
                Return ResourceManager.GetString("fac_ConceptoGestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TANUALIDAD.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarAnualidad() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarAnualidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CH_REC.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarChequeRecido() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarChequeRecido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CPTO_GES.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarConceptoGestion() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarConceptoGestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a COR_MAIL_IN.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarCorrespondencia() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarCorrespondencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DPTO_SERV.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarDepartamentoServicio() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarDepartamentoServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CH_REC_BA.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarDepositoChequeRecidos() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarDepositoChequeRecidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_SERV_DESG.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarDesgloseServicio() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarDesgloseServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DET_ENV.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarDetalleEnvio() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarDetalleEnvio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DET_PG.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarDetallePago() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarDetallePago", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TDOC_MARCA.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarDocumentosMarca() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarDocumentosMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TDOC_PATENTE.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarDocumentosPatente() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarDocumentosPatente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TDOC_TRADUCC.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarDocumentosTraduccion() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarDocumentosTraduccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ETI_FAC.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarEtiqueta() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarEtiqueta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_COBROS.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacCobro() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacCobro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CREDITOS.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacCredito() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacCredito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DETALLES_ANU.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacFactuDetaAnulada() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacFactuDetaAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DETALLES_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacFactuDetaProforma() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacFactuDetaProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_FACTURAS.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacFactura() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacFactura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ANUL.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacFacturaAnulada() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacFacturaAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_FACTURAS_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacFacturaProforma() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacFacturaProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GESTIONES.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacGestion() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacGestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_PRO_CXP.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacInternacionalesProforma() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacInternacionalesProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CONJUST.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacJustificacion() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacJustificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACIONES_ANU.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacOperacionAnulada() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacOperacionAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_ANU.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacOperacionDetaAnulada() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacOperacionDetaAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacOperacionDetalle() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacOperacionDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_TM.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacOperacionDetalleTm() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacOperacionDetalleTm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacOperacionDetaProforma() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacOperacionDetaProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_TM_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacOperacionDetaTmProforma() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacOperacionDetaTmProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACIONES_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacOperacionProforma() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacOperacionProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CXP_BOL.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacPagoBolivia() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacPagoBolivia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TRECURSO.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarFacRecurso() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarFacRecurso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GUIAS.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarGuia() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarGuia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_IMPUESTOS.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarImpuesto() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarImpuesto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TMATERIAL.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarMaterial() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarMaterial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_MEDIO_GES.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarMediosGestion() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarMediosGestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_MOTIVO.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarMotivo() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarMotivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_SERVICIOS.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarServicio() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_SOCIEDAD.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarSociedad() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarSociedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TARIFAS_SERV.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarTarifaServicio() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarTarifaServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TASAS.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarTasa() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarTasa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TIPO_CLASE.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarTipoClase() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarTipoClase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TIPO_MARCA.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarTipoMarca() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarTipoMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TIPO_PATENTE.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarTipoPatente() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarTipoPatente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GESTIONES_CG.
        '''</summary>
        Public Shared ReadOnly Property fac_ConsultarViGestionAsociado() As String
            Get
                Return ResourceManager.GetString("fac_ConsultarViGestionAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a COR_MAIL_IN.
        '''</summary>
        Public Shared ReadOnly Property fac_Correspondencia() As String
            Get
                Return ResourceManager.GetString("fac_Correspondencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DPTO_SERV.
        '''</summary>
        Public Shared ReadOnly Property fac_DepartamentoServicio() As String
            Get
                Return ResourceManager.GetString("fac_DepartamentoServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_SERV_DESG.
        '''</summary>
        Public Shared ReadOnly Property fac_DesgloseServicio() As String
            Get
                Return ResourceManager.GetString("fac_DesgloseServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DET_ENV.
        '''</summary>
        Public Shared ReadOnly Property fac_DetalleEnvio() As String
            Get
                Return ResourceManager.GetString("fac_DetalleEnvio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DET_PG.
        '''</summary>
        Public Shared ReadOnly Property fac_DetallePago() As String
            Get
                Return ResourceManager.GetString("fac_DetallePago", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TDOC_MARCA.
        '''</summary>
        Public Shared ReadOnly Property fac_DocumentosMarca() As String
            Get
                Return ResourceManager.GetString("fac_DocumentosMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TDOC_PATENTE.
        '''</summary>
        Public Shared ReadOnly Property fac_DocumentosPatente() As String
            Get
                Return ResourceManager.GetString("fac_DocumentosPatente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TDOC_TRADUCC.
        '''</summary>
        Public Shared ReadOnly Property fac_DocumentosTraduccion() As String
            Get
                Return ResourceManager.GetString("fac_DocumentosTraduccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ETI_FAC.
        '''</summary>
        Public Shared ReadOnly Property fac_Etiqueta() As String
            Get
                Return ResourceManager.GetString("fac_Etiqueta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_COBROS.
        '''</summary>
        Public Shared ReadOnly Property fac_FacCobro() As String
            Get
                Return ResourceManager.GetString("fac_FacCobro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CREDITOS.
        '''</summary>
        Public Shared ReadOnly Property fac_FacCredito() As String
            Get
                Return ResourceManager.GetString("fac_FacCredito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DETALLES_ANU.
        '''</summary>
        Public Shared ReadOnly Property fac_FacFactuDetaAnulada() As String
            Get
                Return ResourceManager.GetString("fac_FacFactuDetaAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_DETALLES_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_FacFactuDetaProforma() As String
            Get
                Return ResourceManager.GetString("fac_FacFactuDetaProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_FACTURAS.
        '''</summary>
        Public Shared ReadOnly Property fac_FacFactura() As String
            Get
                Return ResourceManager.GetString("fac_FacFactura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ANUL.
        '''</summary>
        Public Shared ReadOnly Property fac_FacFacturaAnulada() As String
            Get
                Return ResourceManager.GetString("fac_FacFacturaAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_FACTURAS_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_FacFacturaProforma() As String
            Get
                Return ResourceManager.GetString("fac_FacFacturaProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GESTIONES.
        '''</summary>
        Public Shared ReadOnly Property fac_FacGestion() As String
            Get
                Return ResourceManager.GetString("fac_FacGestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_PRO_CXP.
        '''</summary>
        Public Shared ReadOnly Property fac_FacInternacionalPago() As String
            Get
                Return ResourceManager.GetString("fac_FacInternacionalPago", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_PRO_CXP.
        '''</summary>
        Public Shared ReadOnly Property fac_FacInternacionalRegistro() As String
            Get
                Return ResourceManager.GetString("fac_FacInternacionalRegistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CONJUST.
        '''</summary>
        Public Shared ReadOnly Property fac_FacJustificacion() As String
            Get
                Return ResourceManager.GetString("fac_FacJustificacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACIONES_ANU.
        '''</summary>
        Public Shared ReadOnly Property fac_FacOperacionAnulada() As String
            Get
                Return ResourceManager.GetString("fac_FacOperacionAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_ANU.
        '''</summary>
        Public Shared ReadOnly Property fac_FacOperacionDetaAnulada() As String
            Get
                Return ResourceManager.GetString("fac_FacOperacionDetaAnulada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET.
        '''</summary>
        Public Shared ReadOnly Property fac_FacOperacionDetalle() As String
            Get
                Return ResourceManager.GetString("fac_FacOperacionDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_TM.
        '''</summary>
        Public Shared ReadOnly Property fac_FacOperacionDetalleTm() As String
            Get
                Return ResourceManager.GetString("fac_FacOperacionDetalleTm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_FacOperacionDetaProforma() As String
            Get
                Return ResourceManager.GetString("fac_FacOperacionDetaProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACION_DET_TM_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_FacOperacionDetaTmProforma() As String
            Get
                Return ResourceManager.GetString("fac_FacOperacionDetaTmProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_OPERACIONES_PRO.
        '''</summary>
        Public Shared ReadOnly Property fac_FacOperacionProforma() As String
            Get
                Return ResourceManager.GetString("fac_FacOperacionProforma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_CXP_BOL.
        '''</summary>
        Public Shared ReadOnly Property fac_FacPagoBolivia() As String
            Get
                Return ResourceManager.GetString("fac_FacPagoBolivia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TRECURSO.
        '''</summary>
        Public Shared ReadOnly Property fac_FacRecurso() As String
            Get
                Return ResourceManager.GetString("fac_FacRecurso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GUIAS.
        '''</summary>
        Public Shared ReadOnly Property fac_Guia() As String
            Get
                Return ResourceManager.GetString("fac_Guia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_IMPUESTOS.
        '''</summary>
        Public Shared ReadOnly Property fac_Impuesto() As String
            Get
                Return ResourceManager.GetString("fac_Impuesto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TMATERIAL.
        '''</summary>
        Public Shared ReadOnly Property fac_Material() As String
            Get
                Return ResourceManager.GetString("fac_Material", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_MEDIOS_GES.
        '''</summary>
        Public Shared ReadOnly Property fac_MediosGestion() As String
            Get
                Return ResourceManager.GetString("fac_MediosGestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACCNASC.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemConsultaCreditosAsociado() As String
            Get
                Return ResourceManager.GetString("fac_menuItemConsultaCreditosAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACCNVGC.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemConsultaCreditosVigentesAsociado() As String
            Get
                Return ResourceManager.GetString("fac_menuItemConsultaCreditosVigentesAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACNDANC.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemConsultaFacturacionAnuladas() As String
            Get
                Return ResourceManager.GetString("fac_menuItemConsultaFacturacionAnuladas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACNDASC.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemConsultaFacturacionAsociado() As String
            Get
                Return ResourceManager.GetString("fac_menuItemConsultaFacturacionAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACNDVGC.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemConsultaFacturacionVigenteAsociado() As String
            Get
                Return ResourceManager.GetString("fac_menuItemConsultaFacturacionVigenteAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ANUL_CON.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemConsultaFacturasAnuladas() As String
            Get
                Return ResourceManager.GetString("fac_menuItemConsultaFacturasAnuladas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACOPASC.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemConsultaOperacionesAsociado() As String
            Get
                Return ResourceManager.GetString("fac_menuItemConsultaOperacionesAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACCRASC.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemConsultaPagosAsociado() As String
            Get
                Return ResourceManager.GetString("fac_menuItemConsultaPagosAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_STATEMENTXPR.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemConsultaStatementPorProcesar() As String
            Get
                Return ResourceManager.GetString("fac_menuItemConsultaStatementPorProcesar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACASOPROF.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemFacAsociadoProfit() As String
            Get
                Return ResourceManager.GetString("fac_menuItemFacAsociadoProfit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACTULOT.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemFacFacturacionLoteVieja() As String
            Get
                Return ResourceManager.GetString("fac_menuItemFacFacturacionLoteVieja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACTUPEND_N.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemFacFacturacionPendiente() As String
            Get
                Return ResourceManager.GetString("fac_menuItemFacFacturacionPendiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACTUPEND.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemFacFacturacionPendienteVieja() As String
            Get
                Return ResourceManager.GetString("fac_menuItemFacFacturacionPendienteVieja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GESTIONES_CN.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemFacGestionesAsociado() As String
            Get
                Return ResourceManager.GetString("fac_menuItemFacGestionesAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACPROFDET.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemFacturaDetalle() As String
            Get
                Return ResourceManager.GetString("fac_menuItemFacturaDetalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACENCPROF.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemFacturaEncabezado() As String
            Get
                Return ResourceManager.GetString("fac_menuItemFacturaEncabezado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACOPRR.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemResumenOperacionesRpt() As String
            Get
                Return ResourceManager.GetString("fac_menuItemResumenOperacionesRpt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACVENR_T.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemVentasTotalesRevRpt() As String
            Get
                Return ResourceManager.GetString("fac_menuItemVentasTotalesRevRpt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FACVENR_TD.
        '''</summary>
        Public Shared ReadOnly Property fac_menuItemVentasTotalesRpt() As String
            Get
                Return ResourceManager.GetString("fac_menuItemVentasTotalesRpt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_MOTIVO.
        '''</summary>
        Public Shared ReadOnly Property fac_Motivo() As String
            Get
                Return ResourceManager.GetString("fac_Motivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_PRO_AUTOFAC.
        '''</summary>
        Public Shared ReadOnly Property fac_proformaafactura() As String
            Get
                Return ResourceManager.GetString("fac_proformaafactura", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_SERVICIOS.
        '''</summary>
        Public Shared ReadOnly Property fac_Servicio() As String
            Get
                Return ResourceManager.GetString("fac_Servicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_SOCIEDAD.
        '''</summary>
        Public Shared ReadOnly Property fac_Sociedad() As String
            Get
                Return ResourceManager.GetString("fac_Sociedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TARIFAS_SERV.
        '''</summary>
        Public Shared ReadOnly Property fac_TarifaServicio() As String
            Get
                Return ResourceManager.GetString("fac_TarifaServicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TASAS.
        '''</summary>
        Public Shared ReadOnly Property fac_Tasa() As String
            Get
                Return ResourceManager.GetString("fac_Tasa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TIPO_CLASE.
        '''</summary>
        Public Shared ReadOnly Property fac_TipoClase() As String
            Get
                Return ResourceManager.GetString("fac_TipoClase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TFECHAS.
        '''</summary>
        Public Shared ReadOnly Property fac_TipoFecha() As String
            Get
                Return ResourceManager.GetString("fac_TipoFecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TINFOBOL.
        '''</summary>
        Public Shared ReadOnly Property fac_TipoInfobol() As String
            Get
                Return ResourceManager.GetString("fac_TipoInfobol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TIPO_MARCA.
        '''</summary>
        Public Shared ReadOnly Property fac_TipoMarca() As String
            Get
                Return ResourceManager.GetString("fac_TipoMarca", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TIPO_PATENTE.
        '''</summary>
        Public Shared ReadOnly Property fac_TipoPatente() As String
            Get
                Return ResourceManager.GetString("fac_TipoPatente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTUSU.
        '''</summary>
        Public Shared ReadOnly Property fac_Usuario() As String
            Get
                Return ResourceManager.GetString("fac_Usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_GESTIONES_CG.
        '''</summary>
        Public Shared ReadOnly Property fac_ViGestionAsociado() As String
            Get
                Return ResourceManager.GetString("fac_ViGestionAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_INTERESADOS.
        '''</summary>
        Public Shared ReadOnly Property Interesado() As String
            Get
                Return ResourceManager.GetString("Interesado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTINAC.
        '''</summary>
        Public Shared ReadOnly Property Internacional() As String
            Get
                Return ResourceManager.GetString("Internacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEG_AUDITORIAS.
        '''</summary>
        Public Shared ReadOnly Property ListaAuditorias() As String
            Get
                Return ResourceManager.GetString("ListaAuditorias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LST_PODERES.
        '''</summary>
        Public Shared ReadOnly Property ListaPoderes() As String
            Get
                Return ResourceManager.GetString("ListaPoderes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_ASOCIADOS.
        '''</summary>
        Public Shared ReadOnly Property ModificarAsociado() As String
            Get
                Return ResourceManager.GetString("ModificarAsociado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTBOLETIN.
        '''</summary>
        Public Shared ReadOnly Property ModificarBoletin() As String
            Get
                Return ResourceManager.GetString("ModificarBoletin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_ESTADOS.
        '''</summary>
        Public Shared ReadOnly Property ModificarEstado() As String
            Get
                Return ResourceManager.GetString("ModificarEstado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TESTADOS.
        '''</summary>
        Public Shared ReadOnly Property ModificarEstatus() As String
            Get
                Return ResourceManager.GetString("ModificarEstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TFECHAS.
        '''</summary>
        Public Shared ReadOnly Property ModificarFecha() As String
            Get
                Return ResourceManager.GetString("ModificarFecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_INTERESADOS.
        '''</summary>
        Public Shared ReadOnly Property ModificarInteresado() As String
            Get
                Return ResourceManager.GetString("ModificarInteresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTINT.
        '''</summary>
        Public Shared ReadOnly Property ModificarInternacional() As String
            Get
                Return ResourceManager.GetString("ModificarInternacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTNAC.
        '''</summary>
        Public Shared ReadOnly Property ModificarNacional() As String
            Get
                Return ResourceManager.GetString("ModificarNacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTOBJ.
        '''</summary>
        Public Shared ReadOnly Property ModificarObjeto() As String
            Get
                Return ResourceManager.GetString("ModificarObjeto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PAISES.
        '''</summary>
        Public Shared ReadOnly Property ModificarPais() As String
            Get
                Return ResourceManager.GetString("ModificarPais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PODERES.
        '''</summary>
        Public Shared ReadOnly Property ModificarPoder() As String
            Get
                Return ResourceManager.GetString("ModificarPoder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_RESOLBOL.
        '''</summary>
        Public Shared ReadOnly Property ModificarResolucion() As String
            Get
                Return ResourceManager.GetString("ModificarResolucion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGMROL.
        '''</summary>
        Public Shared ReadOnly Property ModificarRol() As String
            Get
                Return ResourceManager.GetString("ModificarRol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TINFOBOL.
        '''</summary>
        Public Shared ReadOnly Property ModificarTipoInfobol() As String
            Get
                Return ResourceManager.GetString("ModificarTipoInfobol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTUSU.
        '''</summary>
        Public Shared ReadOnly Property ModificarUsuario() As String
            Get
                Return ResourceManager.GetString("ModificarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYPTNAC.
        '''</summary>
        Public Shared ReadOnly Property Nacional() As String
            Get
                Return ResourceManager.GetString("Nacional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTOBJ.
        '''</summary>
        Public Shared ReadOnly Property Objeto() As String
            Get
                Return ResourceManager.GetString("Objeto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PAISES.
        '''</summary>
        Public Shared ReadOnly Property Pais() As String
            Get
                Return ResourceManager.GetString("Pais", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_PODERES.
        '''</summary>
        Public Shared ReadOnly Property Poder() As String
            Get
                Return ResourceManager.GetString("Poder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_RESOLBOL.
        '''</summary>
        Public Shared ReadOnly Property Resolucion() As String
            Get
                Return ResourceManager.GetString("Resolucion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGMROL.
        '''</summary>
        Public Shared ReadOnly Property Rol() As String
            Get
                Return ResourceManager.GetString("Rol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FAC_TASAS.
        '''</summary>
        Public Shared ReadOnly Property Tasa() As String
            Get
                Return ResourceManager.GetString("Tasa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TFECHAS.
        '''</summary>
        Public Shared ReadOnly Property TipoFecha() As String
            Get
                Return ResourceManager.GetString("TipoFecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MYP_TINFOBOL.
        '''</summary>
        Public Shared ReadOnly Property TipoInfobol() As String
            Get
                Return ResourceManager.GetString("TipoInfobol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEGTUSU.
        '''</summary>
        Public Shared ReadOnly Property Usuario() As String
            Get
                Return ResourceManager.GetString("Usuario", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
